# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AnyCTEssence(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'name': 'str',
        'ver': 'str',
        'wkt': 'str',
        'policy': 'str',
        'cts': 'list[SingleCTEssence]',
        'auth_code': 'AuthCode'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'ver': 'ver',
        'wkt': 'wkt',
        'policy': 'policy',
        'cts': 'cts',
        'auth_code': 'authCode'
    }

    def __init__(self, type=None, name=None, ver=None, wkt=None, policy=None, cts=None, auth_code=None):
        """
        AnyCTEssence - a model defined in Swagger
        """

        self._type = None
        self._name = None
        self._ver = None
        self._wkt = None
        self._policy = None
        self._cts = None
        self._auth_code = None

        self.type = type
        self.name = name
        if ver is not None:
          self.ver = ver
        if wkt is not None:
          self.wkt = wkt
        if policy is not None:
          self.policy = policy
        if cts is not None:
          self.cts = cts
        if auth_code is not None:
          self.auth_code = auth_code

    @property
    def type(self):
        """
        Gets the type of this AnyCTEssence.
        The type identifier, either 'ST' or 'CT'.

        :return: The type of this AnyCTEssence.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this AnyCTEssence.
        The type identifier, either 'ST' or 'CT'.

        :param type: The type of this AnyCTEssence.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")
        allowed_values = ["ST", "CT"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def name(self):
        """
        Gets the name of this AnyCTEssence.
        The name of the simple cartographic transformation.

        :return: The name of this AnyCTEssence.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this AnyCTEssence.
        The name of the simple cartographic transformation.

        :param name: The name of this AnyCTEssence.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def ver(self):
        """
        Gets the ver of this AnyCTEssence.
        The engine version issuing the definition.

        :return: The ver of this AnyCTEssence.
        :rtype: str
        """
        return self._ver

    @ver.setter
    def ver(self, ver):
        """
        Sets the ver of this AnyCTEssence.
        The engine version issuing the definition.

        :param ver: The ver of this AnyCTEssence.
        :type: str
        """

        self._ver = ver

    @property
    def wkt(self):
        """
        Gets the wkt of this AnyCTEssence.
        The well-known text (Esri style) defining this transformation.

        :return: The wkt of this AnyCTEssence.
        :rtype: str
        """
        return self._wkt

    @wkt.setter
    def wkt(self, wkt):
        """
        Sets the wkt of this AnyCTEssence.
        The well-known text (Esri style) defining this transformation.

        :param wkt: The wkt of this AnyCTEssence.
        :type: str
        """

        self._wkt = wkt

    @property
    def policy(self):
        """
        Gets the policy of this AnyCTEssence.
        The transformation policy - concatenated or fallback.

        :return: The policy of this AnyCTEssence.
        :rtype: str
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """
        Sets the policy of this AnyCTEssence.
        The transformation policy - concatenated or fallback.

        :param policy: The policy of this AnyCTEssence.
        :type: str
        """
        allowed_values = ["Fallback", "Concatenated"]
        if policy not in allowed_values:
            raise ValueError(
                "Invalid value for `policy` ({0}), must be one of {1}"
                .format(policy, allowed_values)
            )

        self._policy = policy

    @property
    def cts(self):
        """
        Gets the cts of this AnyCTEssence.
        The ordered list of cartographic transformations.

        :return: The cts of this AnyCTEssence.
        :rtype: list[SingleCTEssence]
        """
        return self._cts

    @cts.setter
    def cts(self, cts):
        """
        Sets the cts of this AnyCTEssence.
        The ordered list of cartographic transformations.

        :param cts: The cts of this AnyCTEssence.
        :type: list[SingleCTEssence]
        """

        self._cts = cts

    @property
    def auth_code(self):
        """
        Gets the auth_code of this AnyCTEssence.
        The authority code for this item.

        :return: The auth_code of this AnyCTEssence.
        :rtype: AuthCode
        """
        return self._auth_code

    @auth_code.setter
    def auth_code(self, auth_code):
        """
        Sets the auth_code of this AnyCTEssence.
        The authority code for this item.

        :param auth_code: The auth_code of this AnyCTEssence.
        :type: AuthCode
        """

        self._auth_code = auth_code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AnyCTEssence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
