# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AnyCRSEssence(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'name': 'str',
        'ver': 'str',
        'wkt': 'str',
        'late_bound_crs': 'LateBoundCRSEssence',
        'single_ct': 'SingleCTEssence',
        'compound_ct': 'CompoundCTEssence',
        'horz_late_bound_crs': 'LateBoundCRSEssence',
        'horz_early_bound_crs': 'EarlyBoundCRSEssence',
        'vert_late_bound_crs': 'LateBoundCRSEssence',
        'vert_early_bound_crs': 'EarlyBoundCRSEssence',
        'auth_code': 'AuthCode'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'ver': 'ver',
        'wkt': 'wkt',
        'late_bound_crs': 'lateBoundCRS',
        'single_ct': 'singleCT',
        'compound_ct': 'compoundCT',
        'horz_late_bound_crs': 'horzLateBoundCRS',
        'horz_early_bound_crs': 'horzEarlyBoundCRS',
        'vert_late_bound_crs': 'vertLateBoundCRS',
        'vert_early_bound_crs': 'vertEarlyBoundCRS',
        'auth_code': 'authCode'
    }

    def __init__(self, type=None, name=None, ver=None, wkt=None, late_bound_crs=None, single_ct=None, compound_ct=None, horz_late_bound_crs=None, horz_early_bound_crs=None, vert_late_bound_crs=None, vert_early_bound_crs=None, auth_code=None):
        """
        AnyCRSEssence - a model defined in Swagger
        """

        self._type = None
        self._name = None
        self._ver = None
        self._wkt = None
        self._late_bound_crs = None
        self._single_ct = None
        self._compound_ct = None
        self._horz_late_bound_crs = None
        self._horz_early_bound_crs = None
        self._vert_late_bound_crs = None
        self._vert_early_bound_crs = None
        self._auth_code = None

        self.type = type
        self.name = name
        if ver is not None:
          self.ver = ver
        if wkt is not None:
          self.wkt = wkt
        if late_bound_crs is not None:
          self.late_bound_crs = late_bound_crs
        if single_ct is not None:
          self.single_ct = single_ct
        if compound_ct is not None:
          self.compound_ct = compound_ct
        if horz_late_bound_crs is not None:
          self.horz_late_bound_crs = horz_late_bound_crs
        if horz_early_bound_crs is not None:
          self.horz_early_bound_crs = horz_early_bound_crs
        if vert_late_bound_crs is not None:
          self.vert_late_bound_crs = vert_late_bound_crs
        if vert_early_bound_crs is not None:
          self.vert_early_bound_crs = vert_early_bound_crs
        if auth_code is not None:
          self.auth_code = auth_code

    @property
    def type(self):
        """
        Gets the type of this AnyCRSEssence.
        The type identifier.

        :return: The type of this AnyCRSEssence.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this AnyCRSEssence.
        The type identifier.

        :param type: The type of this AnyCRSEssence.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")
        allowed_values = ["LBC", "EBC", "CC"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def name(self):
        """
        Gets the name of this AnyCRSEssence.
        The name of the coordinate reference system.

        :return: The name of this AnyCRSEssence.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this AnyCRSEssence.
        The name of the coordinate reference system.

        :param name: The name of this AnyCRSEssence.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def ver(self):
        """
        Gets the ver of this AnyCRSEssence.
        The engine version issuing the definition.

        :return: The ver of this AnyCRSEssence.
        :rtype: str
        """
        return self._ver

    @ver.setter
    def ver(self, ver):
        """
        Sets the ver of this AnyCRSEssence.
        The engine version issuing the definition.

        :param ver: The ver of this AnyCRSEssence.
        :type: str
        """

        self._ver = ver

    @property
    def wkt(self):
        """
        Gets the wkt of this AnyCRSEssence.
        Well-known text (Esri style) of the late-bound coordinate reference system.

        :return: The wkt of this AnyCRSEssence.
        :rtype: str
        """
        return self._wkt

    @wkt.setter
    def wkt(self, wkt):
        """
        Sets the wkt of this AnyCRSEssence.
        Well-known text (Esri style) of the late-bound coordinate reference system.

        :param wkt: The wkt of this AnyCRSEssence.
        :type: str
        """

        self._wkt = wkt

    @property
    def late_bound_crs(self):
        """
        Gets the late_bound_crs of this AnyCRSEssence.
        Late-bound CRS, which is bound to a single (st) or compound (ct) transformation to WGS 84.

        :return: The late_bound_crs of this AnyCRSEssence.
        :rtype: LateBoundCRSEssence
        """
        return self._late_bound_crs

    @late_bound_crs.setter
    def late_bound_crs(self, late_bound_crs):
        """
        Sets the late_bound_crs of this AnyCRSEssence.
        Late-bound CRS, which is bound to a single (st) or compound (ct) transformation to WGS 84.

        :param late_bound_crs: The late_bound_crs of this AnyCRSEssence.
        :type: LateBoundCRSEssence
        """

        self._late_bound_crs = late_bound_crs

    @property
    def single_ct(self):
        """
        Gets the single_ct of this AnyCRSEssence.
        Single Transformation, which binds the late-bound CRS (lb) to WGS 84. If absent, a compound transformation (ct) must be present.

        :return: The single_ct of this AnyCRSEssence.
        :rtype: SingleCTEssence
        """
        return self._single_ct

    @single_ct.setter
    def single_ct(self, single_ct):
        """
        Sets the single_ct of this AnyCRSEssence.
        Single Transformation, which binds the late-bound CRS (lb) to WGS 84. If absent, a compound transformation (ct) must be present.

        :param single_ct: The single_ct of this AnyCRSEssence.
        :type: SingleCTEssence
        """

        self._single_ct = single_ct

    @property
    def compound_ct(self):
        """
        Gets the compound_ct of this AnyCRSEssence.
        Compound transformation, which binds the late-bound CRS (lb) to WGS 84. If absent, a single transformation (st) must be present.

        :return: The compound_ct of this AnyCRSEssence.
        :rtype: CompoundCTEssence
        """
        return self._compound_ct

    @compound_ct.setter
    def compound_ct(self, compound_ct):
        """
        Sets the compound_ct of this AnyCRSEssence.
        Compound transformation, which binds the late-bound CRS (lb) to WGS 84. If absent, a single transformation (st) must be present.

        :param compound_ct: The compound_ct of this AnyCRSEssence.
        :type: CompoundCTEssence
        """

        self._compound_ct = compound_ct

    @property
    def horz_late_bound_crs(self):
        """
        Gets the horz_late_bound_crs of this AnyCRSEssence.
        The horizontal CRS of a Compound CRS as late-bound CRS. If 'horzLateBoundCRS' is non-null, 'horzEarlyBoundCRS' must be null.

        :return: The horz_late_bound_crs of this AnyCRSEssence.
        :rtype: LateBoundCRSEssence
        """
        return self._horz_late_bound_crs

    @horz_late_bound_crs.setter
    def horz_late_bound_crs(self, horz_late_bound_crs):
        """
        Sets the horz_late_bound_crs of this AnyCRSEssence.
        The horizontal CRS of a Compound CRS as late-bound CRS. If 'horzLateBoundCRS' is non-null, 'horzEarlyBoundCRS' must be null.

        :param horz_late_bound_crs: The horz_late_bound_crs of this AnyCRSEssence.
        :type: LateBoundCRSEssence
        """

        self._horz_late_bound_crs = horz_late_bound_crs

    @property
    def horz_early_bound_crs(self):
        """
        Gets the horz_early_bound_crs of this AnyCRSEssence.
        The horizontal CRS of a Compound CRS as early-bound CRS. If 'horzEarlyBoundCRS' is non-null, 'horzLateBoundCRS' must be null.

        :return: The horz_early_bound_crs of this AnyCRSEssence.
        :rtype: EarlyBoundCRSEssence
        """
        return self._horz_early_bound_crs

    @horz_early_bound_crs.setter
    def horz_early_bound_crs(self, horz_early_bound_crs):
        """
        Sets the horz_early_bound_crs of this AnyCRSEssence.
        The horizontal CRS of a Compound CRS as early-bound CRS. If 'horzEarlyBoundCRS' is non-null, 'horzLateBoundCRS' must be null.

        :param horz_early_bound_crs: The horz_early_bound_crs of this AnyCRSEssence.
        :type: EarlyBoundCRSEssence
        """

        self._horz_early_bound_crs = horz_early_bound_crs

    @property
    def vert_late_bound_crs(self):
        """
        Gets the vert_late_bound_crs of this AnyCRSEssence.
        The vertical CRS of the Compound CRS as late-bound CRS. If 'vertLateBoundCRS' is non-null, 'vertEarlyBoundCRS' must be null.

        :return: The vert_late_bound_crs of this AnyCRSEssence.
        :rtype: LateBoundCRSEssence
        """
        return self._vert_late_bound_crs

    @vert_late_bound_crs.setter
    def vert_late_bound_crs(self, vert_late_bound_crs):
        """
        Sets the vert_late_bound_crs of this AnyCRSEssence.
        The vertical CRS of the Compound CRS as late-bound CRS. If 'vertLateBoundCRS' is non-null, 'vertEarlyBoundCRS' must be null.

        :param vert_late_bound_crs: The vert_late_bound_crs of this AnyCRSEssence.
        :type: LateBoundCRSEssence
        """

        self._vert_late_bound_crs = vert_late_bound_crs

    @property
    def vert_early_bound_crs(self):
        """
        Gets the vert_early_bound_crs of this AnyCRSEssence.
        The vertical CRS of the Compound CRS as early-bound CRS. If 'vertEarlyBoundCRS' is non-null, 'vertLateBoundCRS' must be null.

        :return: The vert_early_bound_crs of this AnyCRSEssence.
        :rtype: EarlyBoundCRSEssence
        """
        return self._vert_early_bound_crs

    @vert_early_bound_crs.setter
    def vert_early_bound_crs(self, vert_early_bound_crs):
        """
        Sets the vert_early_bound_crs of this AnyCRSEssence.
        The vertical CRS of the Compound CRS as early-bound CRS. If 'vertEarlyBoundCRS' is non-null, 'vertLateBoundCRS' must be null.

        :param vert_early_bound_crs: The vert_early_bound_crs of this AnyCRSEssence.
        :type: EarlyBoundCRSEssence
        """

        self._vert_early_bound_crs = vert_early_bound_crs

    @property
    def auth_code(self):
        """
        Gets the auth_code of this AnyCRSEssence.
        The authority code for this item.

        :return: The auth_code of this AnyCRSEssence.
        :rtype: AuthCode
        """
        return self._auth_code

    @auth_code.setter
    def auth_code(self, auth_code):
        """
        Sets the auth_code of this AnyCRSEssence.
        The authority code for this item.

        :param auth_code: The auth_code of this AnyCRSEssence.
        :type: AuthCode
        """

        self._auth_code = auth_code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AnyCRSEssence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
