# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AuthCode(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auth': 'str',
        'code': 'str'
    }

    attribute_map = {
        'auth': 'auth',
        'code': 'code'
    }

    def __init__(self, auth='NULL', code='NULL'):
        """
        AuthCode - a model defined in Swagger
        """

        self._auth = None
        self._code = None

        self.auth = auth
        self.code = code

    @property
    def auth(self):
        """
        Gets the auth of this AuthCode.
        The name of the authority issuing the code. Usually a string but it can be NULL for transient items.

        :return: The auth of this AuthCode.
        :rtype: str
        """
        return self._auth

    @auth.setter
    def auth(self, auth):
        """
        Sets the auth of this AuthCode.
        The name of the authority issuing the code. Usually a string but it can be NULL for transient items.

        :param auth: The auth of this AuthCode.
        :type: str
        """
        if auth is None:
            raise ValueError("Invalid value for `auth`, must not be `None`")

        self._auth = auth

    @property
    def code(self):
        """
        Gets the code of this AuthCode.
        The code issued by the authority. Usually a number but it can be NULL for transient items.

        :return: The code of this AuthCode.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this AuthCode.
        The code issued by the authority. Usually a number but it can be NULL for transient items.

        :param code: The code of this AuthCode.
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AuthCode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
