# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Catalog(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'area_of_use_count': 'int',
        'area_of_uses': 'list[AreaOfUse]',
        'attributes': 'CatalogAttributes',
        'compound_c_ts_count': 'int',
        'compound_c_ts': 'list[CompoundCT]',
        'compound_cr_ses_count': 'int',
        'compound_cr_ses': 'list[CompoundCRS]',
        'early_bound_cr_ses_count': 'int',
        'early_bound_cr_ses': 'list[EarlyBoundCRS]',
        'late_bound_cr_ses_count': 'int',
        'late_bound_cr_ses': 'list[LateBoundCRS]',
        'single_c_ts_count': 'int',
        'single_c_ts': 'list[SingleCT]'
    }

    attribute_map = {
        'area_of_use_count': 'areaOfUseCount',
        'area_of_uses': 'areaOfUses',
        'attributes': 'attributes',
        'compound_c_ts_count': 'compoundCTsCount',
        'compound_c_ts': 'compoundCTs',
        'compound_cr_ses_count': 'compoundCRSesCount',
        'compound_cr_ses': 'compoundCRSes',
        'early_bound_cr_ses_count': 'earlyBoundCRSesCount',
        'early_bound_cr_ses': 'earlyBoundCRSes',
        'late_bound_cr_ses_count': 'lateBoundCRSesCount',
        'late_bound_cr_ses': 'lateBoundCRSes',
        'single_c_ts_count': 'singleCTsCount',
        'single_c_ts': 'singleCTs'
    }

    def __init__(self, area_of_use_count=None, area_of_uses=None, attributes=None, compound_c_ts_count=None, compound_c_ts=None, compound_cr_ses_count=None, compound_cr_ses=None, early_bound_cr_ses_count=None, early_bound_cr_ses=None, late_bound_cr_ses_count=None, late_bound_cr_ses=None, single_c_ts_count=None, single_c_ts=None):
        """
        Catalog - a model defined in Swagger
        """

        self._area_of_use_count = None
        self._area_of_uses = None
        self._attributes = None
        self._compound_c_ts_count = None
        self._compound_c_ts = None
        self._compound_cr_ses_count = None
        self._compound_cr_ses = None
        self._early_bound_cr_ses_count = None
        self._early_bound_cr_ses = None
        self._late_bound_cr_ses_count = None
        self._late_bound_cr_ses = None
        self._single_c_ts_count = None
        self._single_c_ts = None

        if area_of_use_count is not None:
          self.area_of_use_count = area_of_use_count
        if area_of_uses is not None:
          self.area_of_uses = area_of_uses
        if attributes is not None:
          self.attributes = attributes
        if compound_c_ts_count is not None:
          self.compound_c_ts_count = compound_c_ts_count
        if compound_c_ts is not None:
          self.compound_c_ts = compound_c_ts
        if compound_cr_ses_count is not None:
          self.compound_cr_ses_count = compound_cr_ses_count
        if compound_cr_ses is not None:
          self.compound_cr_ses = compound_cr_ses
        if early_bound_cr_ses_count is not None:
          self.early_bound_cr_ses_count = early_bound_cr_ses_count
        if early_bound_cr_ses is not None:
          self.early_bound_cr_ses = early_bound_cr_ses
        if late_bound_cr_ses_count is not None:
          self.late_bound_cr_ses_count = late_bound_cr_ses_count
        if late_bound_cr_ses is not None:
          self.late_bound_cr_ses = late_bound_cr_ses
        if single_c_ts_count is not None:
          self.single_c_ts_count = single_c_ts_count
        if single_c_ts is not None:
          self.single_c_ts = single_c_ts

    @property
    def area_of_use_count(self):
        """
        Gets the area_of_use_count of this Catalog.
        The total number of Area Of Uses in the catalog.

        :return: The area_of_use_count of this Catalog.
        :rtype: int
        """
        return self._area_of_use_count

    @area_of_use_count.setter
    def area_of_use_count(self, area_of_use_count):
        """
        Sets the area_of_use_count of this Catalog.
        The total number of Area Of Uses in the catalog.

        :param area_of_use_count: The area_of_use_count of this Catalog.
        :type: int
        """

        self._area_of_use_count = area_of_use_count

    @property
    def area_of_uses(self):
        """
        Gets the area_of_uses of this Catalog.
        The complete list of areas of use.

        :return: The area_of_uses of this Catalog.
        :rtype: list[AreaOfUse]
        """
        return self._area_of_uses

    @area_of_uses.setter
    def area_of_uses(self, area_of_uses):
        """
        Sets the area_of_uses of this Catalog.
        The complete list of areas of use.

        :param area_of_uses: The area_of_uses of this Catalog.
        :type: list[AreaOfUse]
        """

        self._area_of_uses = area_of_uses

    @property
    def attributes(self):
        """
        Gets the attributes of this Catalog.
        The name and last modification time of the catalog.

        :return: The attributes of this Catalog.
        :rtype: CatalogAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """
        Sets the attributes of this Catalog.
        The name and last modification time of the catalog.

        :param attributes: The attributes of this Catalog.
        :type: CatalogAttributes
        """

        self._attributes = attributes

    @property
    def compound_c_ts_count(self):
        """
        Gets the compound_c_ts_count of this Catalog.
        The total number of compoundCTs in the catalog.

        :return: The compound_c_ts_count of this Catalog.
        :rtype: int
        """
        return self._compound_c_ts_count

    @compound_c_ts_count.setter
    def compound_c_ts_count(self, compound_c_ts_count):
        """
        Sets the compound_c_ts_count of this Catalog.
        The total number of compoundCTs in the catalog.

        :param compound_c_ts_count: The compound_c_ts_count of this Catalog.
        :type: int
        """

        self._compound_c_ts_count = compound_c_ts_count

    @property
    def compound_c_ts(self):
        """
        Gets the compound_c_ts of this Catalog.
        The complete list of compound cartographic transforms

        :return: The compound_c_ts of this Catalog.
        :rtype: list[CompoundCT]
        """
        return self._compound_c_ts

    @compound_c_ts.setter
    def compound_c_ts(self, compound_c_ts):
        """
        Sets the compound_c_ts of this Catalog.
        The complete list of compound cartographic transforms

        :param compound_c_ts: The compound_c_ts of this Catalog.
        :type: list[CompoundCT]
        """

        self._compound_c_ts = compound_c_ts

    @property
    def compound_cr_ses_count(self):
        """
        Gets the compound_cr_ses_count of this Catalog.
        The total number of compoundCRSes in the catalog.

        :return: The compound_cr_ses_count of this Catalog.
        :rtype: int
        """
        return self._compound_cr_ses_count

    @compound_cr_ses_count.setter
    def compound_cr_ses_count(self, compound_cr_ses_count):
        """
        Sets the compound_cr_ses_count of this Catalog.
        The total number of compoundCRSes in the catalog.

        :param compound_cr_ses_count: The compound_cr_ses_count of this Catalog.
        :type: int
        """

        self._compound_cr_ses_count = compound_cr_ses_count

    @property
    def compound_cr_ses(self):
        """
        Gets the compound_cr_ses of this Catalog.
        The complete list of compound coordinate reference systems.

        :return: The compound_cr_ses of this Catalog.
        :rtype: list[CompoundCRS]
        """
        return self._compound_cr_ses

    @compound_cr_ses.setter
    def compound_cr_ses(self, compound_cr_ses):
        """
        Sets the compound_cr_ses of this Catalog.
        The complete list of compound coordinate reference systems.

        :param compound_cr_ses: The compound_cr_ses of this Catalog.
        :type: list[CompoundCRS]
        """

        self._compound_cr_ses = compound_cr_ses

    @property
    def early_bound_cr_ses_count(self):
        """
        Gets the early_bound_cr_ses_count of this Catalog.
        The total number of earlyBoundCRSes in the catalog.

        :return: The early_bound_cr_ses_count of this Catalog.
        :rtype: int
        """
        return self._early_bound_cr_ses_count

    @early_bound_cr_ses_count.setter
    def early_bound_cr_ses_count(self, early_bound_cr_ses_count):
        """
        Sets the early_bound_cr_ses_count of this Catalog.
        The total number of earlyBoundCRSes in the catalog.

        :param early_bound_cr_ses_count: The early_bound_cr_ses_count of this Catalog.
        :type: int
        """

        self._early_bound_cr_ses_count = early_bound_cr_ses_count

    @property
    def early_bound_cr_ses(self):
        """
        Gets the early_bound_cr_ses of this Catalog.
        The complete list of early-bound coordinate reference systems.

        :return: The early_bound_cr_ses of this Catalog.
        :rtype: list[EarlyBoundCRS]
        """
        return self._early_bound_cr_ses

    @early_bound_cr_ses.setter
    def early_bound_cr_ses(self, early_bound_cr_ses):
        """
        Sets the early_bound_cr_ses of this Catalog.
        The complete list of early-bound coordinate reference systems.

        :param early_bound_cr_ses: The early_bound_cr_ses of this Catalog.
        :type: list[EarlyBoundCRS]
        """

        self._early_bound_cr_ses = early_bound_cr_ses

    @property
    def late_bound_cr_ses_count(self):
        """
        Gets the late_bound_cr_ses_count of this Catalog.
        The total number of lateBoundCRSes in the catalog.

        :return: The late_bound_cr_ses_count of this Catalog.
        :rtype: int
        """
        return self._late_bound_cr_ses_count

    @late_bound_cr_ses_count.setter
    def late_bound_cr_ses_count(self, late_bound_cr_ses_count):
        """
        Sets the late_bound_cr_ses_count of this Catalog.
        The total number of lateBoundCRSes in the catalog.

        :param late_bound_cr_ses_count: The late_bound_cr_ses_count of this Catalog.
        :type: int
        """

        self._late_bound_cr_ses_count = late_bound_cr_ses_count

    @property
    def late_bound_cr_ses(self):
        """
        Gets the late_bound_cr_ses of this Catalog.
        The complete list of late-bound coordinate reference systems.

        :return: The late_bound_cr_ses of this Catalog.
        :rtype: list[LateBoundCRS]
        """
        return self._late_bound_cr_ses

    @late_bound_cr_ses.setter
    def late_bound_cr_ses(self, late_bound_cr_ses):
        """
        Sets the late_bound_cr_ses of this Catalog.
        The complete list of late-bound coordinate reference systems.

        :param late_bound_cr_ses: The late_bound_cr_ses of this Catalog.
        :type: list[LateBoundCRS]
        """

        self._late_bound_cr_ses = late_bound_cr_ses

    @property
    def single_c_ts_count(self):
        """
        Gets the single_c_ts_count of this Catalog.
        The total number of singleCTs in the catalog.

        :return: The single_c_ts_count of this Catalog.
        :rtype: int
        """
        return self._single_c_ts_count

    @single_c_ts_count.setter
    def single_c_ts_count(self, single_c_ts_count):
        """
        Sets the single_c_ts_count of this Catalog.
        The total number of singleCTs in the catalog.

        :param single_c_ts_count: The single_c_ts_count of this Catalog.
        :type: int
        """

        self._single_c_ts_count = single_c_ts_count

    @property
    def single_c_ts(self):
        """
        Gets the single_c_ts of this Catalog.
        The complete list of single cartographic transforms

        :return: The single_c_ts of this Catalog.
        :rtype: list[SingleCT]
        """
        return self._single_c_ts

    @single_c_ts.setter
    def single_c_ts(self, single_c_ts):
        """
        Sets the single_c_ts of this Catalog.
        The complete list of single cartographic transforms

        :param single_c_ts: The single_c_ts of this Catalog.
        :type: list[SingleCT]
        """

        self._single_c_ts = single_c_ts

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Catalog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
