# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CatalogAttributes(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'last_modified': 'str',
        'name': 'str'
    }

    attribute_map = {
        'description': 'description',
        'last_modified': 'lastModified',
        'name': 'name'
    }

    def __init__(self, description=None, last_modified=None, name=None):
        """
        CatalogAttributes - a model defined in Swagger
        """

        self._description = None
        self._last_modified = None
        self._name = None

        if description is not None:
          self.description = description
        if last_modified is not None:
          self.last_modified = last_modified
        if name is not None:
          self.name = name

    @property
    def description(self):
        """
        Gets the description of this CatalogAttributes.

        :return: The description of this CatalogAttributes.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this CatalogAttributes.

        :param description: The description of this CatalogAttributes.
        :type: str
        """

        self._description = description

    @property
    def last_modified(self):
        """
        Gets the last_modified of this CatalogAttributes.
        The last modification date and time (UTC) of this catalog.

        :return: The last_modified of this CatalogAttributes.
        :rtype: str
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """
        Sets the last_modified of this CatalogAttributes.
        The last modification date and time (UTC) of this catalog.

        :param last_modified: The last_modified of this CatalogAttributes.
        :type: str
        """

        self._last_modified = last_modified

    @property
    def name(self):
        """
        Gets the name of this CatalogAttributes.
        Name of the catalog

        :return: The name of this CatalogAttributes.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CatalogAttributes.
        Name of the catalog

        :param name: The name of this CatalogAttributes.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CatalogAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
