# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NamedReference(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'persistable_reference': 'str'
    }

    attribute_map = {
        'name': 'name',
        'persistable_reference': 'persistableReference'
    }

    def __init__(self, name=None, persistable_reference=None):
        """
        NamedReference - a model defined in Swagger
        """

        self._name = None
        self._persistable_reference = None

        if name is not None:
          self.name = name
        if persistable_reference is not None:
          self.persistable_reference = persistable_reference

    @property
    def name(self):
        """
        Gets the name of this NamedReference.
        The name of the item.

        :return: The name of this NamedReference.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this NamedReference.
        The name of the item.

        :param name: The name of this NamedReference.
        :type: str
        """

        self._name = name

    @property
    def persistable_reference(self):
        """
        Gets the persistable_reference of this NamedReference.
        The item 'essence' serialized into a JSON string.

        :return: The persistable_reference of this NamedReference.
        :rtype: str
        """
        return self._persistable_reference

    @persistable_reference.setter
    def persistable_reference(self, persistable_reference):
        """
        Sets the persistable_reference of this NamedReference.
        The item 'essence' serialized into a JSON string.

        :param persistable_reference: The persistable_reference of this NamedReference.
        :type: str
        """

        self._persistable_reference = persistable_reference

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NamedReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
