# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SingleCT(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source': 'str',
        'alias_names': 'list[str]',
        'description': 'str',
        'from_crs_authority_code': 'AuthCode',
        'to_crs_authority_code': 'AuthCode',
        'last_modified': 'str',
        'area_of_use': 'AreaOfUse',
        'deprecation_info': 'CTDeprecationInfo',
        'named_reference': 'NamedReference',
        'essence': 'SingleCTEssence'
    }

    attribute_map = {
        'source': 'source',
        'alias_names': 'aliasNames',
        'description': 'description',
        'from_crs_authority_code': 'fromCRSAuthorityCode',
        'to_crs_authority_code': 'toCRSAuthorityCode',
        'last_modified': 'lastModified',
        'area_of_use': 'areaOfUse',
        'deprecation_info': 'deprecationInfo',
        'named_reference': 'namedReference',
        'essence': 'essence'
    }

    def __init__(self, source=None, alias_names=None, description=None, from_crs_authority_code=None, to_crs_authority_code=None, last_modified=None, area_of_use=None, deprecation_info=None, named_reference=None, essence=None):
        """
        SingleCT - a model defined in Swagger
        """

        self._source = None
        self._alias_names = None
        self._description = None
        self._from_crs_authority_code = None
        self._to_crs_authority_code = None
        self._last_modified = None
        self._area_of_use = None
        self._deprecation_info = None
        self._named_reference = None
        self._essence = None

        if source is not None:
          self.source = source
        if alias_names is not None:
          self.alias_names = alias_names
        if description is not None:
          self.description = description
        if from_crs_authority_code is not None:
          self.from_crs_authority_code = from_crs_authority_code
        if to_crs_authority_code is not None:
          self.to_crs_authority_code = to_crs_authority_code
        if last_modified is not None:
          self.last_modified = last_modified
        if area_of_use is not None:
          self.area_of_use = area_of_use
        if deprecation_info is not None:
          self.deprecation_info = deprecation_info
        if named_reference is not None:
          self.named_reference = named_reference
        if essence is not None:
          self.essence = essence

    @property
    def source(self):
        """
        Gets the source of this SingleCT.
        The source of the SingleCT.

        :return: The source of this SingleCT.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this SingleCT.
        The source of the SingleCT.

        :param source: The source of this SingleCT.
        :type: str
        """

        self._source = source

    @property
    def alias_names(self):
        """
        Gets the alias_names of this SingleCT.
        Alias names for this SingleCT.

        :return: The alias_names of this SingleCT.
        :rtype: list[str]
        """
        return self._alias_names

    @alias_names.setter
    def alias_names(self, alias_names):
        """
        Sets the alias_names of this SingleCT.
        Alias names for this SingleCT.

        :param alias_names: The alias_names of this SingleCT.
        :type: list[str]
        """

        self._alias_names = alias_names

    @property
    def description(self):
        """
        Gets the description of this SingleCT.
        The description of the SingleCT.

        :return: The description of this SingleCT.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this SingleCT.
        The description of the SingleCT.

        :param description: The description of this SingleCT.
        :type: str
        """

        self._description = description

    @property
    def from_crs_authority_code(self):
        """
        Gets the from_crs_authority_code of this SingleCT.
        The 'from CRS' authority code of this SingleCT.

        :return: The from_crs_authority_code of this SingleCT.
        :rtype: AuthCode
        """
        return self._from_crs_authority_code

    @from_crs_authority_code.setter
    def from_crs_authority_code(self, from_crs_authority_code):
        """
        Sets the from_crs_authority_code of this SingleCT.
        The 'from CRS' authority code of this SingleCT.

        :param from_crs_authority_code: The from_crs_authority_code of this SingleCT.
        :type: AuthCode
        """

        self._from_crs_authority_code = from_crs_authority_code

    @property
    def to_crs_authority_code(self):
        """
        Gets the to_crs_authority_code of this SingleCT.
        The 'to CRS' authority code of this SingleCT.

        :return: The to_crs_authority_code of this SingleCT.
        :rtype: AuthCode
        """
        return self._to_crs_authority_code

    @to_crs_authority_code.setter
    def to_crs_authority_code(self, to_crs_authority_code):
        """
        Sets the to_crs_authority_code of this SingleCT.
        The 'to CRS' authority code of this SingleCT.

        :param to_crs_authority_code: The to_crs_authority_code of this SingleCT.
        :type: AuthCode
        """

        self._to_crs_authority_code = to_crs_authority_code

    @property
    def last_modified(self):
        """
        Gets the last_modified of this SingleCT.
        The LastModified of the SingleCT.

        :return: The last_modified of this SingleCT.
        :rtype: str
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """
        Sets the last_modified of this SingleCT.
        The LastModified of the SingleCT.

        :param last_modified: The last_modified of this SingleCT.
        :type: str
        """

        self._last_modified = last_modified

    @property
    def area_of_use(self):
        """
        Gets the area_of_use of this SingleCT.
        The Area of Use for this SingleCT.

        :return: The area_of_use of this SingleCT.
        :rtype: AreaOfUse
        """
        return self._area_of_use

    @area_of_use.setter
    def area_of_use(self, area_of_use):
        """
        Sets the area_of_use of this SingleCT.
        The Area of Use for this SingleCT.

        :param area_of_use: The area_of_use of this SingleCT.
        :type: AreaOfUse
        """

        self._area_of_use = area_of_use

    @property
    def deprecation_info(self):
        """
        Gets the deprecation_info of this SingleCT.
        Only if deprecated - additional information and potentially a recommended replacement CT.

        :return: The deprecation_info of this SingleCT.
        :rtype: CTDeprecationInfo
        """
        return self._deprecation_info

    @deprecation_info.setter
    def deprecation_info(self, deprecation_info):
        """
        Sets the deprecation_info of this SingleCT.
        Only if deprecated - additional information and potentially a recommended replacement CT.

        :param deprecation_info: The deprecation_info of this SingleCT.
        :type: CTDeprecationInfo
        """

        self._deprecation_info = deprecation_info

    @property
    def named_reference(self):
        """
        Gets the named_reference of this SingleCT.
        A structure containing the item Name and the persistable Reference string; populated if the request mode='persistable_reference'.

        :return: The named_reference of this SingleCT.
        :rtype: NamedReference
        """
        return self._named_reference

    @named_reference.setter
    def named_reference(self, named_reference):
        """
        Sets the named_reference of this SingleCT.
        A structure containing the item Name and the persistable Reference string; populated if the request mode='persistable_reference'.

        :param named_reference: The named_reference of this SingleCT.
        :type: NamedReference
        """

        self._named_reference = named_reference

    @property
    def essence(self):
        """
        Gets the essence of this SingleCT.
        The Essence of the SingleCT.

        :return: The essence of this SingleCT.
        :rtype: SingleCTEssence
        """
        return self._essence

    @essence.setter
    def essence(self, essence):
        """
        Sets the essence of this SingleCT.
        The Essence of the SingleCT.

        :param essence: The essence of this SingleCT.
        :type: SingleCTEssence
        """

        self._essence = essence

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SingleCT):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
