data:
  # configmaps
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  # deployments
  requestsCpu: "0.1"
  requestsMemory: "256M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"

conf:
  appName: "crs-catalog"
  onPremEnabled: false
  domain: ""

istio:
  proxyCPU: "50m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
