data:
  requests_cpu: "0.25"
  requests_memory: "256M"
  limits_cpu: "1"
  limits_memory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "crs-catalog-config"
  app_name: "crs-catalog"
