variables:
  # --- osdu-gcp specific variables ---
  OSDU_GCP_SERVICE: crs-catalog
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: os-crs-catalog
  OSDU_GCP_INT_TEST_TYPE: python
  OSDU_GCP_PYTHON_INT_TEST_SUBDIR: testing/catalog_test_gcp
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"
  OSDU_GCP_HELM_DEPLOYMENT_DIR: "devops/gcp/deploy"
  OSDU_GCP_HELM_CONFIG_DIR: "devops/gcp/configmap"
  OSDU_GCP_HELM_NAMESPACE: default
  OSDU_GCP_HELM_CONFIG_SERVICE: crs-catalog-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: crs-catalog-deploy
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: >
    --set data.project_id=$OSDU_GCP_PROJECT 
    --set data.audiences=$GOOGLE_AUDIENCE 
    --set data.google_audiences=$GOOGLE_AUDIENCE
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: >
    --set data.project_id=$OSDU_GCP_PROJECT 
    --set data.audiences=$GOOGLE_AUDIENCE 
    --set data.google_audiences=$GOOGLE_AUDIENCE
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: >
    --set data.image=$CI_REGISTRY_IMAGE/osdu-gcp-$OSDU_GCP_SERVICE:$CI_COMMIT_SHORT_SHA 
    --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s
  # --- end of osdu-gcp specific variables ---

  # --- osdu-anthos specific variables ---
  OSDU_ANTHOS_PYTHON_INT_TEST_SUBDIR: testing/catalog_test_anthos
  # --- end of osdu-anthos specific variables ---



osdu-gcp-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CATALOG_HOSTNAME

osdu-gcp-dev2-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CATALOG_HOSTNAME

osdu-gcp-anthos-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_ANTHOS_CRS_CATALOG_HOSTNAME
