variables:
  OSDU_GCP_SERVICE: crs-catalog
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_INT_TEST_TYPE: python
  OSDU_GCP_PYTHON_INT_TEST_SUBDIR: testing/catalog_test_gcp
  # --- osdu-anthos specific variables ---
  OSDU_ANTHOS_PYTHON_INT_TEST_SUBDIR: testing/catalog_test_anthos
  # --- end of osdu-anthos specific variables ---

osdu-gcp-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CATALOG_HOSTNAME

osdu-gcp-dev2-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CATALOG_HOSTNAME

osdu-gcp-anthos-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_ANTHOS_CRS_CATALOG_HOSTNAME
