#Manage common SpringDoc and OpenAPI related properties

#SpringDoc related properties
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.displayOperationId=true
springdoc.api-docs.path=/api-docs

#OpenAPI 3.0 - CRS Catalog properties
api.title=CRS Catalog Service API
api.description=Coordinate Reference System (CRS) Catalog Service
api.version=1.0.0
api.contact.name=OSDU Data Platform Team
api.contact.email=dps@OSDU.org
api.license.name=Apache 2.0
api.license.url=https://www.apache.org/licenses/LICENSE-2.0.html
api.server.url=${server.servlet.contextPath}

#Info & Health API related properties V2
infoApi.info.summary=info
infoApi.info.description=For deployment available public `/info` endpoint, which provides build and git related information.

healthCheckApi.livenessCheck.summary=Liveness Check endpoint
healthCheckApi.livenessCheck.description=For deployment available public `/liveness_check` endpoint, which provides `CRS Catalog Service is alive` message.
healthCheckApi.readinessCheck.summary=Readiness Check endpoint
healthCheckApi.readinessCheck.description=For deployment available public `/readiness_check` endpoint, which provides `CRS Catalog Service is ready` message.

CrsCatalogApi.Catalog.summary=Get the Catalog summary (without lists)
CrsCatalogApi.Catalog.description=Get the catalog structure with populated number of items per list but empty lists ('lateBoundCRSes',...). It is expected that the lists are individually populated on demand via the specific methods ('CRSV2GetLateBoundCRSes',...).

CrsCatalogApi.CatalogAttributes.summary=Get Catalog Name and Update Dates
CrsCatalogApi.CatalogAttributes.description=Get the catalog name and last update date

CrsCatalogApi.AllArea.summary=Get Areas of Use
CrsCatalogApi.AllArea.description=Get Area of Use records - returning named bounding box definitions in latitude and longitude.

CrsCatalogApi.OneArea.summary=Get one Area of Use
CrsCatalogApi.OneArea.description=Get one Area of Use record by essence - returning a named bounding box definition in latitude and longitude.

CrsCatalogApi.SearchAreaOfUse.summary=Search Areas of Use
CrsCatalogApi.SearchAreaOfUse.description=Search Area of Use records by keywords and/or geographic area - returning named bounding box definitions in latitude and longitude. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: ''name:'', ''description:'', ''authority:'', ''code:'', ''deprecationState:'', ''remarks:'' (deprecationState remarks), ''lastModified:''. Example ''name:*America*''.

CrsCatalogApi.CoordinateReferenceSystems.summary=Get all CRSes
CrsCatalogApi.CoordinateReferenceSystems.description=Get all the CRSes (any sub-type) defined in the catalog.
CrsCatalogApi.CoordinateReferenceSystemsOne.summary=Get one CRS
CrsCatalogApi.CoordinateReferenceSystemsOne.description=Get one CRS (any sub-type) given its essence

CrsCatalogApi.LateBoundCRS.summary=Get all LateBoundCRSes
CrsCatalogApi.LateBoundCRS.description=Get all the LateBoundCRSes defined in the catalog.
CrsCatalogApi.OneLateBoundCRS.summary=Get one LateBoundCRS
CrsCatalogApi.OneLateBoundCRS.description=Get one LateBoundCRS given its persistable reference string or essence structure.

CrsCatalogApi.SearchCRS.summary=Search CRSes
CrsCatalogApi.SearchCRS.description=Search CRS records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: ''name:'', ''description:'', ''type:'', ''authority:'', ''code:'', ''deprecationState:'', ''remarks:'', ''lastModified:'', ''source:'', ''wellKnownText:'', ''crsType:'', ''baseCRS.authority:'', ''baseCRS.code:'', ''horizontalCRS.authority:'', ''horizontalCRS.code:'', ''verticalCRS.authority:'', ''verticalCRS.code:'', ''lateBoundCRS.authority:'', ''lateBoundCRS.code:'', ''ct.authority:'', ''ct.code:'', ''transformationReady:''. followed by a value. Example: ''transformationReady:true''.

CrsCatalogApi.EarlyBoundCRS.summary=Get all EarlyBoundCRSes
CrsCatalogApi.EarlyBoundCRS.description=Get all the EarlyBoundCRSes defined in the catalog.
CrsCatalogApi.OneEarlyBoundCRS.summary=Get all EarlyBoundCRSes
CrsCatalogApi.OneEarlyBoundCRS.description=Get all the EarlyBoundCRSes defined in the catalog.

CrsCatalogApi.CompoundCRS.summary=Get all CompoundCRSes
CrsCatalogApi.CompoundCRS.description=Get all the CompoundCRSes defined in the catalog
CrsCatalogApi.OneCompoundCRS.summary=Get One CompoundCRSes
CrsCatalogApi.OneCompoundCRS.description=Get one the CompoundCRS given its essence.

CrsCatalogApi.CT.summary=Get all Cartographic Transformations
CrsCatalogApi.CT.description=Get all cartographic transformations declared in the catalog.
CrsCatalogApi.OneCT.summary=Get one Cartographic Transformation
CrsCatalogApi.OneCT.description=Get one cartographic transformation given its essence.

CrsCatalogApi.SingleCT.summary=Get all SingleCTs
CrsCatalogApi.SingleCT.description=Get all the SingleCTs defined in the catalog.
CrsCatalogApi.OneSingleCT.summary=Get one SingleCT
CrsCatalogApi.OneSingleCT.description=Get one SingleCT given its essence.

CrsCatalogApi.CompoundCT.summary=Get all CompoundCTs
CrsCatalogApi.CompoundCT.description=Get all the CompoundCTs defined in the catalog.
CrsCatalogApi.OneCompoundCT.summary=Get One CompoundCTs
CrsCatalogApi.OneCompoundCT.description=Get one CompoundCT by its essence.

CrsCatalogApi.SearchCT.summary=Search Cartographic Transformations
CrsCatalogApi.SearchCT.description=Search cartographic transform records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: ''name:'',''description:'', ''type:'', ''authority:'', ''code:'', ''deprecationState:'', ''remarks:'', ''lastModified:'', ''source:'', ''wellKnownText:'', ''fromCRS.authority:'', ''fromCRS.code:'', ''toCRS.authority:'', toCRS.code:'', ''policy:''. followed by a value. Example: ''fromCRS.code:4267''.

# Version-3
infoApi.infoV3.summary=info
infoApi.infoV3.description=For deployment available public `/info` endpoint, which provides build and git related information..

CrsCatalogApiV3.CoordinateTransformation.summary=Coordinate Transformations
CrsCatalogApiV3.CoordinateTransformation.description=Coordinate Transformations
CrsCatalogApiV3.CoordinateTransformations.summary=Coordinate Transformations
CrsCatalogApiV3.CoordinateTransformations.description=Coordinate Transformations

CrsCatalogApiV3.CoordinateReferenceSystem.summary=Coordinate Reference Systems
CrsCatalogApiV3.CoordinateReferenceSystem.description=Coordinate Reference Systems
CrsCatalogApiV3.CoordinateReferenceSystems.summary=Coordinate Transformations
CrsCatalogApiV3.CoordinateReferenceSystems.description=Coordinate Transformations

CrsCatalogApiV3.PointsInAOUSearch.summary=Area Of Use
CrsCatalogApiV3.PointsInAOUSearch.description=Area Of Use

