AWS_BUILD_SUBDIR: provider/crs-catalog-aws/build-aws
AWS_TEST_SUBDIR: testing/catalog_test_aws
AWS_SERVICE: crs-catalog
AWS_ENVIRONMENT: dev
AWS_INT_TEST_TYPE: python

include:
  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'standard-setup.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'build/maven.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'scanners/fossa.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'scanners/gitlab-ultimate.yml'

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws.yml"
