variables:
  # --- osdu-gcp specific variables ---
  OSDU_GCP_SERVICE: crs-catalog
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: os-crs-catalog
  OSDU_GCP_INT_TEST_TYPE: python
  OSDU_GCP_PYTHON_INT_TEST_SUBDIR: testing/catalog_test_gcp
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"
  OSDU_GCP_HELM_DEPLOYMENT_DIR: "devops/gcp/deploy"
  OSDU_GCP_HELM_CONFIG_DIR: "devops/gcp/configmap"
  OSDU_GCP_HELM_NAMESPACE: default
  OSDU_GCP_HELM_CONFIG_SERVICE: crs-catalog-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: crs-catalog-deploy
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: "--set data.project_id=$OSDU_GCP_PROJECT --set data.audiences=$GOOGLE_AUDIENCE --set data.google_audiences=$GOOGLE_AUDIENCE"
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: "--set data.project_id=$OSDU_GCP_PROJECT --set data.audiences=$GOOGLE_AUDIENCE --set data.google_audiences=$GOOGLE_AUDIENCE"
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: "--set data.image=$CI_REGISTRY_IMAGE/osdu-gcp:$CI_COMMIT_SHORT_SHA --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s"
  # --- end of osdu-gcp specific variables ---

  AWS_BUILD_SUBDIR: provider/crs-catalog-aws/build-aws
  AWS_TEST_SUBDIR: testing/catalog_test_aws
  AWS_SERVICE: crs-catalog
  AWS_ENVIRONMENT: dev
  AWS_INT_TEST_TYPE: python
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-crs-catalog

  IBM_BUILD_SUBDIR: provider/crs-catalog-ibm/crs-catalog-ocp
  IBM_INT_TEST_PY_SUBDIR: testing/catalog_test_ibm
  IBM_INT_TEST_PY_FILE: run_test.py

  #azure
  AZURE_SERVICE: crs_catalog
  AZURE_BUILD_SUBDIR: provider/crs-catalog-azure/crs-catalog-aks
  AZURE_TEST_SUBDIR: testing/catalog_test_azure
  AZURE_TEST_TYPE: python
  SHARE_NAME: crs

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-gke.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-python-test.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
  
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-python.yml"

osdu-gcp-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CATALOG_HOSTNAME

osdu-gcp-dev2-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CATALOG_HOSTNAME
