include:
  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'standard-setup.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'build/maven.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'scanners/fossa.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'scanners/gitlab-ultimate.yml'
