# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class AreasOfUseApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def get_all_areas_of_use(self, **kwargs):
        """
        Get Areas of Use
        Get Area of Use records - returning named bounding box definitions in latitude and longitude.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_areas_of_use(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all AreaOfUse. It is optional and is 0 by default.
        :param int limit: The maximum number of the AreaOfUse returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: AreaOfUseResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_all_areas_of_use_with_http_info(**kwargs)
        else:
            (data) = self.get_all_areas_of_use_with_http_info(**kwargs)
            return data

    def get_all_areas_of_use_with_http_info(self, **kwargs):
        """
        Get Areas of Use
        Get Area of Use records - returning named bounding box definitions in latitude and longitude.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_areas_of_use_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all AreaOfUse. It is optional and is 0 by default.
        :param int limit: The maximum number of the AreaOfUse returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: AreaOfUseResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_areas_of_use" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token', 'sauth_id_token']

        return self.api_client.call_api('/area', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AreaOfUseResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_one_area_of_use(self, **kwargs):
        """
        Get one Area of Use
        Get one Area of Use record by essence - returning a named bounding box definition in latitude and longitude.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_area_of_use(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param AreaOfUseRequest body: A unique description of an AreaOfUse, either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: AreaOfUse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_one_area_of_use_with_http_info(**kwargs)
        else:
            (data) = self.get_one_area_of_use_with_http_info(**kwargs)
            return data

    def get_one_area_of_use_with_http_info(self, **kwargs):
        """
        Get one Area of Use
        Get one Area of Use record by essence - returning a named bounding box definition in latitude and longitude.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_area_of_use_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param AreaOfUseRequest body: A unique description of an AreaOfUse, either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: AreaOfUse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_one_area_of_use" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token', 'sauth_id_token']

        return self.api_client.call_api('/area', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AreaOfUse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def search_area_of_use(self, body, **kwargs):
        """
        Search Areas of Use
        Search Area of Use records by keywords and/or geographic area - returning named bounding box definitions in latitude and longitude. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: 'name:', 'description:', 'authority:', 'code:', 'deprecationState:', 'remarks:' (deprecationState remarks), 'lastModified:'. Example 'name:*America*'.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.search_area_of_use(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param SearchAreaOfUseRequest body: A Lucene style keyword query. One of the following keywords: 'name:', 'description:', 'authority:', 'code:', 'deprecationState:', 'remarks:' (deprecationState remarks), 'lastModified:'. Example 'name:*America*'. (required)
        :param float longitude_left: The left WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_lower: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param float longitude_right: The right WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_upper: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param int offset: The offset of the first item in the list of all AreasOfUse. It is optional and is 0 by default.
        :param int limit: The maximum number of the AreasOfUse returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: AreaOfUseResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.search_area_of_use_with_http_info(body, **kwargs)
        else:
            (data) = self.search_area_of_use_with_http_info(body, **kwargs)
            return data

    def search_area_of_use_with_http_info(self, body, **kwargs):
        """
        Search Areas of Use
        Search Area of Use records by keywords and/or geographic area - returning named bounding box definitions in latitude and longitude. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: 'name:', 'description:', 'authority:', 'code:', 'deprecationState:', 'remarks:' (deprecationState remarks), 'lastModified:'. Example 'name:*America*'.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.search_area_of_use_with_http_info(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param SearchAreaOfUseRequest body: A Lucene style keyword query. One of the following keywords: 'name:', 'description:', 'authority:', 'code:', 'deprecationState:', 'remarks:' (deprecationState remarks), 'lastModified:'. Example 'name:*America*'. (required)
        :param float longitude_left: The left WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_lower: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param float longitude_right: The right WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_upper: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param int offset: The offset of the first item in the list of all AreasOfUse. It is optional and is 0 by default.
        :param int limit: The maximum number of the AreasOfUse returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: AreaOfUseResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'longitude_left', 'latitude_lower', 'longitude_right', 'latitude_upper', 'offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_area_of_use" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `search_area_of_use`")


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'longitude_left' in params:
            query_params.append(('longitudeLeft', params['longitude_left']))
        if 'latitude_lower' in params:
            query_params.append(('latitudeLower', params['latitude_lower']))
        if 'longitude_right' in params:
            query_params.append(('longitudeRight', params['longitude_right']))
        if 'latitude_upper' in params:
            query_params.append(('latitudeUpper', params['latitude_upper']))
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token', 'sauth_id_token']

        return self.api_client.call_api('/search/area', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AreaOfUseResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
