# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class CartographicTransformationsApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def get_all_compound_ct(self, **kwargs):
        """
        Get all CompoundCTs
        Get all the CompoundCTs defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_compound_ct(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all CompoundCTs. It is optional and is 0 by default.
        :param int limit: The maximum number of the CompoundCTs returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CompoundCTResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_all_compound_ct_with_http_info(**kwargs)
        else:
            (data) = self.get_all_compound_ct_with_http_info(**kwargs)
            return data

    def get_all_compound_ct_with_http_info(self, **kwargs):
        """
        Get all CompoundCTs
        Get all the CompoundCTs defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_compound_ct_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all CompoundCTs. It is optional and is 0 by default.
        :param int limit: The maximum number of the CompoundCTs returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CompoundCTResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_compound_ct" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/compoundct', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CompoundCTResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_all_ct(self, **kwargs):
        """
        Get all Cartographic Transformations
        Get all cartographic transformations declared in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_ct(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all CT. It is optional and is 0 by default.
        :param int limit: The maximum number of the CT returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CTResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_all_ct_with_http_info(**kwargs)
        else:
            (data) = self.get_all_ct_with_http_info(**kwargs)
            return data

    def get_all_ct_with_http_info(self, **kwargs):
        """
        Get all Cartographic Transformations
        Get all cartographic transformations declared in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_ct_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all CT. It is optional and is 0 by default.
        :param int limit: The maximum number of the CT returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CTResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_ct" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/ct', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CTResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_all_single_ct(self, **kwargs):
        """
        Get all SingleCTs
        Get all the SingleCTs defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_single_ct(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all SingleCTs. It is optional and is 0 by default.
        :param int limit: The maximum number of the SingleCTs returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: SingleCTResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_all_single_ct_with_http_info(**kwargs)
        else:
            (data) = self.get_all_single_ct_with_http_info(**kwargs)
            return data

    def get_all_single_ct_with_http_info(self, **kwargs):
        """
        Get all SingleCTs
        Get all the SingleCTs defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_single_ct_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all SingleCTs. It is optional and is 0 by default.
        :param int limit: The maximum number of the SingleCTs returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: SingleCTResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_single_ct" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/singlect', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='SingleCTResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_one_compound_ct(self, **kwargs):
        """
        Get one CompoundCT
        Get one CompoundCT by its essence.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_compound_ct(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param CompoundCTRequest body: A unique description of a compound cartographic transform (CompoundCT), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CompoundCT
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_one_compound_ct_with_http_info(**kwargs)
        else:
            (data) = self.get_one_compound_ct_with_http_info(**kwargs)
            return data

    def get_one_compound_ct_with_http_info(self, **kwargs):
        """
        Get one CompoundCT
        Get one CompoundCT by its essence.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_compound_ct_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param CompoundCTRequest body: A unique description of a compound cartographic transform (CompoundCT), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CompoundCT
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_one_compound_ct" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/compoundct', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CompoundCT',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_one_ct(self, **kwargs):
        """
        Get one Cartographic Transformation
        Get one cartographic transformation given its essence
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_ct(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param CTRequest body: A unique description of a cartographic transform (CT), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CT
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_one_ct_with_http_info(**kwargs)
        else:
            (data) = self.get_one_ct_with_http_info(**kwargs)
            return data

    def get_one_ct_with_http_info(self, **kwargs):
        """
        Get one Cartographic Transformation
        Get one cartographic transformation given its essence
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_ct_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param CTRequest body: A unique description of a cartographic transform (CT), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CT
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_one_ct" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/ct', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CT',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_one_single_ct(self, **kwargs):
        """
        Get one SingleCT
        Get one SingleCT given its essence.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_single_ct(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param SingleCTRequest body: A unique description of a single cartographic transform (SingleCT), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: SingleCT
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_one_single_ct_with_http_info(**kwargs)
        else:
            (data) = self.get_one_single_ct_with_http_info(**kwargs)
            return data

    def get_one_single_ct_with_http_info(self, **kwargs):
        """
        Get one SingleCT
        Get one SingleCT given its essence.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_single_ct_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param SingleCTRequest body: A unique description of a single cartographic transform (SingleCT), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: SingleCT
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_one_single_ct" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/singlect', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='SingleCT',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def search_ct(self, body, **kwargs):
        """
        Search Cartographic Transformations
        Search cartographic transform records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: 'name:','description:', 'type:', 'authority:', 'code:', 'deprecationState:', 'remarks:', 'lastModified:', 'source:', 'wellKnownText:', 'fromCRS.authority:', 'fromCRS.code:', 'toCRS.authority:', toCRS.code:', 'policy:'. followed by a value. Example: 'fromCRS.code:4267'.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.search_ct(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param SearchCTRequest body: A Lucene style keyword query. One of the following keywords 'name:','description:', 'type:', 'authority:', 'code:', 'deprecationState:', 'remarks:', 'lastModified:', 'source:', 'wellKnownText:', 'fromCRS.authority:', 'fromCRS.code:', 'toCRS.authority:', toCRS.code:', 'policy:'. followed by a value. Example: 'fromCRS.code:4267'. (required)
        :param float longitude_left: The left WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_lower: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param float longitude_right: The right WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_upper: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param int offset: The offset of the first item in the list of all CT. It is optional and is 0 by default.
        :param int limit: The maximum number of the CT returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CTResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.search_ct_with_http_info(body, **kwargs)
        else:
            (data) = self.search_ct_with_http_info(body, **kwargs)
            return data

    def search_ct_with_http_info(self, body, **kwargs):
        """
        Search Cartographic Transformations
        Search cartographic transform records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: 'name:','description:', 'type:', 'authority:', 'code:', 'deprecationState:', 'remarks:', 'lastModified:', 'source:', 'wellKnownText:', 'fromCRS.authority:', 'fromCRS.code:', 'toCRS.authority:', toCRS.code:', 'policy:'. followed by a value. Example: 'fromCRS.code:4267'.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.search_ct_with_http_info(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param SearchCTRequest body: A Lucene style keyword query. One of the following keywords 'name:','description:', 'type:', 'authority:', 'code:', 'deprecationState:', 'remarks:', 'lastModified:', 'source:', 'wellKnownText:', 'fromCRS.authority:', 'fromCRS.code:', 'toCRS.authority:', toCRS.code:', 'policy:'. followed by a value. Example: 'fromCRS.code:4267'. (required)
        :param float longitude_left: The left WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_lower: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param float longitude_right: The right WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_upper: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param int offset: The offset of the first item in the list of all CT. It is optional and is 0 by default.
        :param int limit: The maximum number of the CT returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CTResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'longitude_left', 'latitude_lower', 'longitude_right', 'latitude_upper', 'offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_ct" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `search_ct`")


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'longitude_left' in params:
            query_params.append(('longitudeLeft', params['longitude_left']))
        if 'latitude_lower' in params:
            query_params.append(('latitudeLower', params['latitude_lower']))
        if 'longitude_right' in params:
            query_params.append(('longitudeRight', params['longitude_right']))
        if 'latitude_upper' in params:
            query_params.append(('latitudeUpper', params['latitude_upper']))
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/search/ct', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CTResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
