# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class CoordinateReferenceSystemsApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def get_all_compound_crs(self, **kwargs):
        """
        Get all CompoundCRSes
        Get all the CompoundCRSes defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_compound_crs(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all CompoundCRSes. It is optional and is 0 by default.
        :param int limit: The maximum number of the CompoundCRSes returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CompoundCRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_all_compound_crs_with_http_info(**kwargs)
        else:
            (data) = self.get_all_compound_crs_with_http_info(**kwargs)
            return data

    def get_all_compound_crs_with_http_info(self, **kwargs):
        """
        Get all CompoundCRSes
        Get all the CompoundCRSes defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_compound_crs_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all CompoundCRSes. It is optional and is 0 by default.
        :param int limit: The maximum number of the CompoundCRSes returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CompoundCRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_compound_crs" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/compoundcrs', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CompoundCRSResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_all_crs(self, **kwargs):
        """
        Get all CRSes
        Get all the CRSes (any sub-type) defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_crs(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all CRSes. It is optional and is 0 by default.
        :param int limit: The maximum number of the CRSes returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_all_crs_with_http_info(**kwargs)
        else:
            (data) = self.get_all_crs_with_http_info(**kwargs)
            return data

    def get_all_crs_with_http_info(self, **kwargs):
        """
        Get all CRSes
        Get all the CRSes (any sub-type) defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_crs_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all CRSes. It is optional and is 0 by default.
        :param int limit: The maximum number of the CRSes returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_crs" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/crs', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CRSResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_all_early_bound_crs(self, **kwargs):
        """
        Get all EarlyBoundCRSes
        Get all the EarlyBoundCRSes defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_early_bound_crs(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all EarlyBoundCRSes. It is optional and is 0 by default.
        :param int limit: The maximum number of the EarlyBoundCRSes returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: EarlyBoundCRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_all_early_bound_crs_with_http_info(**kwargs)
        else:
            (data) = self.get_all_early_bound_crs_with_http_info(**kwargs)
            return data

    def get_all_early_bound_crs_with_http_info(self, **kwargs):
        """
        Get all EarlyBoundCRSes
        Get all the EarlyBoundCRSes defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_early_bound_crs_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all EarlyBoundCRSes. It is optional and is 0 by default.
        :param int limit: The maximum number of the EarlyBoundCRSes returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: EarlyBoundCRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_early_bound_crs" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/earlyboundcrs', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='EarlyBoundCRSResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_all_late_bound_crs(self, **kwargs):
        """
        Get all LateBoundCRSes
        Get all the LateBoundCRSes defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_late_bound_crs(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all LateBoundCRSes. It is optional and is 0 by default.
        :param int limit: The maximum number of the LateBoundCRSes returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: LateBoundCRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_all_late_bound_crs_with_http_info(**kwargs)
        else:
            (data) = self.get_all_late_bound_crs_with_http_info(**kwargs)
            return data

    def get_all_late_bound_crs_with_http_info(self, **kwargs):
        """
        Get all LateBoundCRSes
        Get all the LateBoundCRSes defined in the catalog.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_all_late_bound_crs_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int offset: The offset of the first item in the list of all LateBoundCRSes. It is optional and is 0 by default.
        :param int limit: The maximum number of the LateBoundCRSes returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: LateBoundCRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_late_bound_crs" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']


        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/lateboundcrs', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='LateBoundCRSResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_one_compound_crs(self, **kwargs):
        """
        Get one CompoundCRS
        Get one the CompoundCRS given its essence.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_compound_crs(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param CompoundCRSRequest body: A unique description of a compound coordinate reference system (CompoundCRS), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CompoundCRS
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_one_compound_crs_with_http_info(**kwargs)
        else:
            (data) = self.get_one_compound_crs_with_http_info(**kwargs)
            return data

    def get_one_compound_crs_with_http_info(self, **kwargs):
        """
        Get one CompoundCRS
        Get one the CompoundCRS given its essence.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_compound_crs_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param CompoundCRSRequest body: A unique description of a compound coordinate reference system (CompoundCRS), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CompoundCRS
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_one_compound_crs" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']


        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/compoundcrs', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CompoundCRS',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_one_crs(self, **kwargs):
        """
        Get one CRS
        Get one CRS (any sub-type) given its essence
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_crs(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param CRSRequest body: A unique description of a coordinate reference system (CRS), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CRS
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_one_crs_with_http_info(**kwargs)
        else:
            (data) = self.get_one_crs_with_http_info(**kwargs)
            return data

    def get_one_crs_with_http_info(self, **kwargs):
        """
        Get one CRS
        Get one CRS (any sub-type) given its essence
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_crs_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param CRSRequest body: A unique description of a coordinate reference system (CRS), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CRS
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_one_crs" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']


        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/crs', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CRS',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_one_early_bound_crs(self, **kwargs):
        """
        Get one EarlyBoundCRS
        Get one EarlyBoundCRS given its essence
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_early_bound_crs(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param EarlyBoundCRSRequest body: A unique description of a early-bound coordinate reference system (EarlyBoundCRS), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: EarlyBoundCRS
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_one_early_bound_crs_with_http_info(**kwargs)
        else:
            (data) = self.get_one_early_bound_crs_with_http_info(**kwargs)
            return data

    def get_one_early_bound_crs_with_http_info(self, **kwargs):
        """
        Get one EarlyBoundCRS
        Get one EarlyBoundCRS given its essence
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_early_bound_crs_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param EarlyBoundCRSRequest body: A unique description of a early-bound coordinate reference system (EarlyBoundCRS), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: EarlyBoundCRS
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_one_early_bound_crs" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']


        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/earlyboundcrs', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='EarlyBoundCRS',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_one_late_bound_crs(self, **kwargs):
        """
        Get one LateBoundCRS
        Get one LateBoundCRS given its persistable reference string or essence structure.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_late_bound_crs(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param LateBoundCRSRequest body: A unique description of a late-bound coordinate reference system (LateBoundCRS), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: LateBoundCRS
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_one_late_bound_crs_with_http_info(**kwargs)
        else:
            (data) = self.get_one_late_bound_crs_with_http_info(**kwargs)
            return data

    def get_one_late_bound_crs_with_http_info(self, **kwargs):
        """
        Get one LateBoundCRS
        Get one LateBoundCRS given its persistable reference string or essence structure.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_one_late_bound_crs_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param LateBoundCRSRequest body: A unique description of a late-bound coordinate reference system (LateBoundCRS), either as persistable reference string or essence JSON.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: LateBoundCRS
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_one_late_bound_crs" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']


        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/lateboundcrs', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='LateBoundCRS',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def search_crs(self, body, **kwargs):
        """
        Search CRSes
        Search CRS records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: 'name:', 'description:', 'type:', 'authority:', 'code:', 'deprecationState:', 'remarks:', 'lastModified:', 'source:', 'wellKnownText:', 'crsType:', 'baseCRS.authority:', 'baseCRS.code:', 'horizontalCRS.authority:', 'horizontalCRS.code:', 'verticalCRS.authority:', 'verticalCRS.code:', 'lateBoundCRS.authority:', 'lateBoundCRS.code:', 'ct.authority:', 'ct.code:', 'transformationReady:'. followed by a value. Example: 'transformationReady:true'.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.search_crs(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param SearchCRSRequest body: A Lucene style keyword query. One of the following keywords 'name:', 'description:', 'type:', 'authority:', 'code:', 'deprecationState:', 'remarks:', 'lastModified:', 'source:', 'wellKnownText:', 'crsType:', 'baseCRS.authority:', 'baseCRS.code:', 'horizontalCRS.authority:', 'horizontalCRS.code:', 'verticalCRS.authority:', 'verticalCRS.code:', 'lateBoundCRS.authority:', 'lateBoundCRS.code:', 'ct.authority:', 'ct.code:', 'transformationReady:'. followed by a value. Example: 'transformationReady:true'. (required)
        :param float longitude_left: The left WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_lower: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param float longitude_right: The right WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_upper: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param int offset: The offset of the first item in the list of all CRS. It is optional and is 0 by default.
        :param int limit: The maximum number of the CRS returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.search_crs_with_http_info(body, **kwargs)
        else:
            (data) = self.search_crs_with_http_info(body, **kwargs)
            return data

    def search_crs_with_http_info(self, body, **kwargs):
        """
        Search CRSes
        Search CRS records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: 'name:', 'description:', 'type:', 'authority:', 'code:', 'deprecationState:', 'remarks:', 'lastModified:', 'source:', 'wellKnownText:', 'crsType:', 'baseCRS.authority:', 'baseCRS.code:', 'horizontalCRS.authority:', 'horizontalCRS.code:', 'verticalCRS.authority:', 'verticalCRS.code:', 'lateBoundCRS.authority:', 'lateBoundCRS.code:', 'ct.authority:', 'ct.code:', 'transformationReady:'. followed by a value. Example: 'transformationReady:true'.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.search_crs_with_http_info(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param SearchCRSRequest body: A Lucene style keyword query. One of the following keywords 'name:', 'description:', 'type:', 'authority:', 'code:', 'deprecationState:', 'remarks:', 'lastModified:', 'source:', 'wellKnownText:', 'crsType:', 'baseCRS.authority:', 'baseCRS.code:', 'horizontalCRS.authority:', 'horizontalCRS.code:', 'verticalCRS.authority:', 'verticalCRS.code:', 'lateBoundCRS.authority:', 'lateBoundCRS.code:', 'ct.authority:', 'ct.code:', 'transformationReady:'. followed by a value. Example: 'transformationReady:true'. (required)
        :param float longitude_left: The left WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_lower: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param float longitude_right: The right WGS 84 longitude limit of the search box. Value range: [-180,180]
        :param float latitude_upper: The lower WGS 84 latitude limit of the search box. Value range: [-90,90]
        :param int offset: The offset of the first item in the list of all CRS. It is optional and is 0 by default.
        :param int limit: The maximum number of the CRS returned. It is optional and is 100 by default.
        :param str mode: The mode of return: 'persistable_reference' (default) string or 'essence' structure or both 'persistable_reference_essence'.
        :param str data_partition_id:
        :return: CRSResults
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'longitude_left', 'latitude_lower', 'longitude_right', 'latitude_upper', 'offset', 'limit', 'mode', 'data_partition_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_crs" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `search_crs`")


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'longitude_left' in params:
            query_params.append(('longitudeLeft', params['longitude_left']))
        if 'latitude_lower' in params:
            query_params.append(('latitudeLower', params['latitude_lower']))
        if 'longitude_right' in params:
            query_params.append(('longitudeRight', params['longitude_right']))
        if 'latitude_upper' in params:
            query_params.append(('latitudeUpper', params['latitude_upper']))
        if 'offset' in params:
            query_params.append(('offset', params['offset']))
        if 'limit' in params:
            query_params.append(('limit', params['limit']))
        if 'mode' in params:
            query_params.append(('mode', params['mode']))

        header_params = {}
        if 'data_partition_id' in params:
            header_params['data-partition-id'] = params['data_partition_id']


        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer', 'google_id_token']

        return self.api_client.call_api('/search/crs', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CRSResults',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
