global:
  domain: ""
  onPremEnabled: false
  limitsEnabled: true

data:
  # configmaps
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  # deployments
  requestsCpu: "5m"
  requestsMemory: "280Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"

conf:
  appName: "crs-catalog"

istio:
  proxyCPU: "5m"
  proxyCPULimit: "200m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "256Mi"
