data:
  # configmaps
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  # deployments
  requestsCpu: "25m"
  requestsMemory: "352Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"

conf:
  appName: "crs-catalog"
  onPremEnabled: false
  domain: ""

istio:
  proxyCPU: "10m"
  proxyCPULimit: "200m"
  proxyMemory: "32Mi"
  proxyMemoryLimit: "256Mi"
