global:
  domain: ""
  onPremEnabled: false
  limitsEnabled: true
  logLevel: "ERROR"
  tier: ""
  autoscaling: true

data:
  # configmaps
  logLevel: ""
  entitlementsHost: "http://entitlements"
  # deployments
  requestsCpu: "5m"
  requestsMemory: "280Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"

conf:
  appName: "crs-catalog"
  replicas: 2

istio:
  proxyCPU: "5m"
  proxyCPULimit: "200m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "256Mi"

hpa:
  minReplicas: 3
  maxReplicas: 15
  targetType: "AverageValue"
  targetValue: 130
  behaviorScaleUpStabilizationWindowSeconds: 10
  behaviorScaleUpPoliciesValue: 50
  behaviorScaleUpPoliciesPeriodSeconds: 15
  behaviorScaleDownStabilizationWindowSeconds: 60
  behaviorScaleDownPoliciesValue: 25
  behaviorScaleDownPoliciesPeriodSeconds: 60

limits:
  maxTokens: 98
  tokensPerFill: 98
  fillInterval: "1s"
