{{- template "common.authzpolicy" (list . "os-crs-catalog.authzpolicy") -}}
{{- define "os-crs-catalog.authzpolicy" -}}
## Define overrides for the service authorization policy resource here
{{- end -}}

