{{- template "common.serviceparameters" (list . "os-crs-catalog.serviceparameters") -}}
{{- define "os-crs-catalog.serviceparameters" -}}
## Define overrides for the service parameters here
{{- end -}}