{{- template "common.serviceaccount" (list . "os-crs-catalog.serviceaccount") -}}
{{- define "os-crs-catalog.serviceaccount" -}}
## Define overrides for the service's service account resource here
{{- end -}}