# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.crs_catalog_api import CRSCatalogApi


class TestCRSCatalogApi(unittest.TestCase):
    """ CRSCatalogApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.crs_catalog_api.CRSCatalogApi()

    def tearDown(self):
        pass

    def test_get_catalog_attributes(self):
        """
        Test case for get_catalog_attributes

        Get Catalog Name and Update Dates
        """
        pass

    def test_get_catalog_summary(self):
        """
        Test case for get_catalog_summary

        Get the Catalog summary (without lists)
        """
        pass


if __name__ == '__main__':
    unittest.main()
