# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.cartographic_transformations_api import CartographicTransformationsApi


class TestCartographicTransformationsApi(unittest.TestCase):
    """ CartographicTransformationsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.cartographic_transformations_api.CartographicTransformationsApi()

    def tearDown(self):
        pass

    def test_get_all_compound_ct(self):
        """
        Test case for get_all_compound_ct

        Get all CompoundCTs
        """
        pass

    def test_get_all_ct(self):
        """
        Test case for get_all_ct

        Get all Cartographic Transformations
        """
        pass

    def test_get_all_single_ct(self):
        """
        Test case for get_all_single_ct

        Get all SingleCTs
        """
        pass

    def test_get_one_compound_ct(self):
        """
        Test case for get_one_compound_ct

        Get one CompoundCT
        """
        pass

    def test_get_one_ct(self):
        """
        Test case for get_one_ct

        Get one Cartographic Transformation
        """
        pass

    def test_get_one_single_ct(self):
        """
        Test case for get_one_single_ct

        Get one SingleCT
        """
        pass

    def test_search_ct(self):
        """
        Test case for search_ct

        Search Cartographic Transformations
        """
        pass


if __name__ == '__main__':
    unittest.main()
