# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.coordinate_reference_systems_api import CoordinateReferenceSystemsApi


class TestCoordinateReferenceSystemsApi(unittest.TestCase):
    """ CoordinateReferenceSystemsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.coordinate_reference_systems_api.CoordinateReferenceSystemsApi()

    def tearDown(self):
        pass

    def test_get_all_compound_crs(self):
        """
        Test case for get_all_compound_crs

        Get all CompoundCRSes
        """
        pass

    def test_get_all_crs(self):
        """
        Test case for get_all_crs

        Get all CRSes
        """
        pass

    def test_get_all_early_bound_crs(self):
        """
        Test case for get_all_early_bound_crs

        Get all EarlyBoundCRSes
        """
        pass

    def test_get_all_late_bound_crs(self):
        """
        Test case for get_all_late_bound_crs

        Get all LateBoundCRSes
        """
        pass

    def test_get_one_compound_crs(self):
        """
        Test case for get_one_compound_crs

        Get one CompoundCRS
        """
        pass

    def test_get_one_crs(self):
        """
        Test case for get_one_crs

        Get one CRS
        """
        pass

    def test_get_one_early_bound_crs(self):
        """
        Test case for get_one_early_bound_crs

        Get one EarlyBoundCRS
        """
        pass

    def test_get_one_late_bound_crs(self):
        """
        Test case for get_one_late_bound_crs

        Get one LateBoundCRS
        """
        pass

    def test_search_crs(self):
        """
        Test case for search_crs

        Search CRSes
        """
        pass


if __name__ == '__main__':
    unittest.main()
