# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.crs_deprecation_info import CRSDeprecationInfo


class TestCRSDeprecationInfo(unittest.TestCase):
    """ CRSDeprecationInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCRSDeprecationInfo(self):
        """
        Test CRSDeprecationInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.crs_deprecation_info.CRSDeprecationInfo()
        pass


if __name__ == '__main__':
    unittest.main()
