LOG_PREFIX=crs-catalog

server.servlet.contextPath=/api/crs/catalog/
logging.level.org.springframework.web=DEBUG
server.port=8080

# Entitlement properties
#
#
# [Required] URL of the Entitlements Service
osdu.entitlement.url=${ENTITLEMENT_URL}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloack.certs.uri}

osdu.search.url=${SEARCH_API}

# Other properties
#
#
# [Optional] [AKS] [GKE] File location of the crs catalog
osdu.crs.catalog.filename=${CRS_CATALOG_FILENAME:/mnt/crs_catalog_catalogs/crs_catalog_v2.json}
