# Copyright 2017-2019, Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "crs-catalog-aks"
  namespace: {{ .Values.namespace }}
  labels:
    app: "crs-catalog-aks"
    version: v2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "crs-catalog-aks"
      version: v2
  template:
    metadata:
      labels:
        app: "crs-catalog-aks"
        version: v2
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: shared-data
            mountPath: /mnt/crs_catalogs
          ports:
            - name: http
              containerPort: {{ .Values.service.http.targetPort }}
            - name: https
              containerPort: {{ .Values.service.https.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ENTITLEMENT_URL
              value: "{{.Values.service.entitlement.url}}" 
      initContainers:
      - name: "init-crs-catalog"
        image: "{{ .Values.catalogs.repository }}:{{ .Values.catalogs.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/crs_catalogs
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
