global:
  replicaCount: 1

image:
  repository: ${CONTAINER_REGISTRY_NAME}.azurecr.io/crs-catalog-app
  tag: latest
  pullPolicy: Always

catalog:
  repository: ${CONTAINER_REGISTRY_NAME}.azurecr.io/crs-catalog-data
  tag: v2
  pullPolicy: Always


