global:
  replicaCount: 1

image:
  imagePullSecrets: acr

app:
  repository: delfi.azurecr.io/crs-catalog-app
  tag: latest
  pullPolicy: Always

catalog:
  repository: delfi.azurecr.io/crs-catalogs
  tag: v2
  pullPolicy: Always


