LOG_PREFIX=crs-catalog

server.servlet.contextPath=/api/crs/catalog/
logging.level.org.springframework.web=DEBUG
server.port=8080

spring.main.allow-bean-definition-overriding=true

#spring.cloud.gcp.project-id=opendes
#spring.security.user.roles=service.crs.admin
JAVA_HEAP_OPTS=-Xms4096M -Xmx4096M
JAVA_GC_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitiatingHeapOccupancyPercent=45

# Entitlement properties
#
#
# [Required] URL of the Entitlements Service
osdu.entitlement.url=${ENTITLEMENT_URL}

# Other properties
#
#
# [Optional] [AKS] [GKE] File location of the crs catalog
osdu.crs.catalog.filename=${CRS_CATALOG_FILENAME:/mnt/crs_catalogs/crs_catalog_v2.json}
# CRS_CATALOG_FILENAME=C:\\osdu-delfi\\os-crs-catalog-service\\data\\crs_catalog_v2.json

# ENTITLEMENT_URL=https://ado-devint-d-dwe06kgl-au-entitlements.azurewebsites.net/
# CRS_CATALOG_FILENAME=C:\\osdu-delfi\\os-crs-catalog-service\\data\\crs_catalog_v2.json

# PROJECT_ID=opendes
# REGION=us-central1
# ENTITLEMENT_URL=https://entitlements-dot-opendes.appspot.com/entitlements/v1
# CRS_CATALOG_HOSTNAME=os-crs-catalog-dot-opendes.appspot.com
# AUDIENCES=245464679631-ktfdfpl147m1mjpbutl00b3cmffissgq.apps.googleusercontent.com
