# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.compound_crs_essence import CompoundCRSEssence


class TestCompoundCRSEssence(unittest.TestCase):
    """ CompoundCRSEssence unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompoundCRSEssence(self):
        """
        Test CompoundCRSEssence
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.compound_crs_essence.CompoundCRSEssence()
        pass


if __name__ == '__main__':
    unittest.main()
