# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.area_of_use_request import AreaOfUseRequest


class TestAreaOfUseRequest(unittest.TestCase):
    """ AreaOfUseRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAreaOfUseRequest(self):
        """
        Test AreaOfUseRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.area_of_use_request.AreaOfUseRequest()
        pass


if __name__ == '__main__':
    unittest.main()
