# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.area_of_use_essence import AreaOfUseEssence


class TestAreaOfUseEssence(unittest.TestCase):
    """ AreaOfUseEssence unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAreaOfUseEssence(self):
        """
        Test AreaOfUseEssence
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.area_of_use_essence.AreaOfUseEssence()
        pass


if __name__ == '__main__':
    unittest.main()
