# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.areas_of_use_api import AreasOfUseApi


class TestAreasOfUseApi(unittest.TestCase):
    """ AreasOfUseApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.areas_of_use_api.AreasOfUseApi()

    def tearDown(self):
        pass

    def test_get_all_areas_of_use(self):
        """
        Test case for get_all_areas_of_use

        Get Areas of Use
        """
        pass

    def test_get_one_area_of_use(self):
        """
        Test case for get_one_area_of_use

        Get one Area of Use
        """
        pass

    def test_search_area_of_use(self):
        """
        Test case for search_area_of_use

        Search Areas of Use
        """
        pass


if __name__ == '__main__':
    unittest.main()
