# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AreaOfUseEssence(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'bound_box': 'BoundBox',
        'auth_code': 'AuthCode'
    }

    attribute_map = {
        'type': 'type',
        'bound_box': 'boundBox',
        'auth_code': 'authCode'
    }

    def __init__(self, type='AOU', bound_box=None, auth_code=None):
        """
        AreaOfUseEssence - a model defined in Swagger
        """

        self._type = None
        self._bound_box = None
        self._auth_code = None

        self.type = type
        self.bound_box = bound_box
        if auth_code is not None:
          self.auth_code = auth_code

    @property
    def type(self):
        """
        Gets the type of this AreaOfUseEssence.
        The type identifier, fixed to 'AOU'.

        :return: The type of this AreaOfUseEssence.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this AreaOfUseEssence.
        The type identifier, fixed to 'AOU'.

        :param type: The type of this AreaOfUseEssence.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")
        allowed_values = ["AOU"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def bound_box(self):
        """
        Gets the bound_box of this AreaOfUseEssence.
        The bounding box in latitude and longitude WGS 84 based.

        :return: The bound_box of this AreaOfUseEssence.
        :rtype: BoundBox
        """
        return self._bound_box

    @bound_box.setter
    def bound_box(self, bound_box):
        """
        Sets the bound_box of this AreaOfUseEssence.
        The bounding box in latitude and longitude WGS 84 based.

        :param bound_box: The bound_box of this AreaOfUseEssence.
        :type: BoundBox
        """
        if bound_box is None:
            raise ValueError("Invalid value for `bound_box`, must not be `None`")

        self._bound_box = bound_box

    @property
    def auth_code(self):
        """
        Gets the auth_code of this AreaOfUseEssence.
        The authority code for this item.

        :return: The auth_code of this AreaOfUseEssence.
        :rtype: AuthCode
        """
        return self._auth_code

    @auth_code.setter
    def auth_code(self, auth_code):
        """
        Sets the auth_code of this AreaOfUseEssence.
        The authority code for this item.

        :param auth_code: The auth_code of this AreaOfUseEssence.
        :type: AuthCode
        """

        self._auth_code = auth_code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AreaOfUseEssence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
