# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AreaOfUse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'last_modified': 'str',
        'named_reference': 'NamedReference',
        'essence': 'AreaOfUseEssence'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'last_modified': 'lastModified',
        'named_reference': 'namedReference',
        'essence': 'essence'
    }

    def __init__(self, id=None, name=None, description=None, last_modified=None, named_reference=None, essence=None):
        """
        AreaOfUse - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._description = None
        self._last_modified = None
        self._named_reference = None
        self._essence = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if description is not None:
          self.description = description
        if last_modified is not None:
          self.last_modified = last_modified
        if named_reference is not None:
          self.named_reference = named_reference
        if essence is not None:
          self.essence = essence

    @property
    def id(self):
        """
        Gets the id of this AreaOfUse.
        The Internal Id of the AreaOfUse.

        :return: The id of this AreaOfUse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this AreaOfUse.
        The Internal Id of the AreaOfUse.

        :param id: The id of this AreaOfUse.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this AreaOfUse.
        The name of the AreaOfUse.

        :return: The name of this AreaOfUse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this AreaOfUse.
        The name of the AreaOfUse.

        :param name: The name of this AreaOfUse.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this AreaOfUse.
        The description of the AreaOfUse.

        :return: The description of this AreaOfUse.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this AreaOfUse.
        The description of the AreaOfUse.

        :param description: The description of this AreaOfUse.
        :type: str
        """

        self._description = description

    @property
    def last_modified(self):
        """
        Gets the last_modified of this AreaOfUse.
        The LastModified of the AreaOfUse.

        :return: The last_modified of this AreaOfUse.
        :rtype: str
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """
        Sets the last_modified of this AreaOfUse.
        The LastModified of the AreaOfUse.

        :param last_modified: The last_modified of this AreaOfUse.
        :type: str
        """

        self._last_modified = last_modified

    @property
    def named_reference(self):
        """
        Gets the named_reference of this AreaOfUse.
        A structure containing the item Name and the persistable Reference string; populated if the request mode='persistable_reference'.

        :return: The named_reference of this AreaOfUse.
        :rtype: NamedReference
        """
        return self._named_reference

    @named_reference.setter
    def named_reference(self, named_reference):
        """
        Sets the named_reference of this AreaOfUse.
        A structure containing the item Name and the persistable Reference string; populated if the request mode='persistable_reference'.

        :param named_reference: The named_reference of this AreaOfUse.
        :type: NamedReference
        """

        self._named_reference = named_reference

    @property
    def essence(self):
        """
        Gets the essence of this AreaOfUse.
        The Essence of the AreaOfUse.

        :return: The essence of this AreaOfUse.
        :rtype: AreaOfUseEssence
        """
        return self._essence

    @essence.setter
    def essence(self, essence):
        """
        Sets the essence of this AreaOfUse.
        The Essence of the AreaOfUse.

        :param essence: The essence of this AreaOfUse.
        :type: AreaOfUseEssence
        """

        self._essence = essence

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AreaOfUse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
