# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BoundBox(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lon_min': 'float',
        'lon_max': 'float',
        'lat_min': 'float',
        'lat_max': 'float'
    }

    attribute_map = {
        'lon_min': 'lonMin',
        'lon_max': 'lonMax',
        'lat_min': 'latMin',
        'lat_max': 'latMax'
    }

    def __init__(self, lon_min=None, lon_max=None, lat_min=None, lat_max=None):
        """
        BoundBox - a model defined in Swagger
        """

        self._lon_min = None
        self._lon_max = None
        self._lat_min = None
        self._lat_max = None

        self.lon_min = lon_min
        self.lon_max = lon_max
        self.lat_min = lat_min
        self.lat_max = lat_max

    @property
    def lon_min(self):
        """
        Gets the lon_min of this BoundBox.
        The left longitude limit in degrees; the longitude can wrap around the datum line.

        :return: The lon_min of this BoundBox.
        :rtype: float
        """
        return self._lon_min

    @lon_min.setter
    def lon_min(self, lon_min):
        """
        Sets the lon_min of this BoundBox.
        The left longitude limit in degrees; the longitude can wrap around the datum line.

        :param lon_min: The lon_min of this BoundBox.
        :type: float
        """
        if lon_min is None:
            raise ValueError("Invalid value for `lon_min`, must not be `None`")

        self._lon_min = lon_min

    @property
    def lon_max(self):
        """
        Gets the lon_max of this BoundBox.
        The right longitude limit in degrees; the longitude can wrap around the datum line.

        :return: The lon_max of this BoundBox.
        :rtype: float
        """
        return self._lon_max

    @lon_max.setter
    def lon_max(self, lon_max):
        """
        Sets the lon_max of this BoundBox.
        The right longitude limit in degrees; the longitude can wrap around the datum line.

        :param lon_max: The lon_max of this BoundBox.
        :type: float
        """
        if lon_max is None:
            raise ValueError("Invalid value for `lon_max`, must not be `None`")

        self._lon_max = lon_max

    @property
    def lat_min(self):
        """
        Gets the lat_min of this BoundBox.
        The upper latitude limit in degrees.

        :return: The lat_min of this BoundBox.
        :rtype: float
        """
        return self._lat_min

    @lat_min.setter
    def lat_min(self, lat_min):
        """
        Sets the lat_min of this BoundBox.
        The upper latitude limit in degrees.

        :param lat_min: The lat_min of this BoundBox.
        :type: float
        """
        if lat_min is None:
            raise ValueError("Invalid value for `lat_min`, must not be `None`")

        self._lat_min = lat_min

    @property
    def lat_max(self):
        """
        Gets the lat_max of this BoundBox.
        The lower latitude limit in degrees.

        :return: The lat_max of this BoundBox.
        :rtype: float
        """
        return self._lat_max

    @lat_max.setter
    def lat_max(self, lat_max):
        """
        Sets the lat_max of this BoundBox.
        The lower latitude limit in degrees.

        :param lat_max: The lat_max of this BoundBox.
        :type: float
        """
        if lat_max is None:
            raise ValueError("Invalid value for `lat_max`, must not be `None`")

        self._lat_max = lat_max

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BoundBox):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
