# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CRSDeprecationInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'deprecation_state': 'str',
        'remarks': 'str',
        'superseded_by_crs': 'CRS'
    }

    attribute_map = {
        'deprecation_state': 'deprecationState',
        'remarks': 'remarks',
        'superseded_by_crs': 'supersededByCRS'
    }

    def __init__(self, deprecation_state=None, remarks=None, superseded_by_crs=None):
        """
        CRSDeprecationInfo - a model defined in Swagger
        """

        self._deprecation_state = None
        self._remarks = None
        self._superseded_by_crs = None

        if deprecation_state is not None:
          self.deprecation_state = deprecation_state
        if remarks is not None:
          self.remarks = remarks
        if superseded_by_crs is not None:
          self.superseded_by_crs = superseded_by_crs

    @property
    def deprecation_state(self):
        """
        Gets the deprecation_state of this CRSDeprecationInfo.
        State - one of {identical, corrected, unresolved}

        :return: The deprecation_state of this CRSDeprecationInfo.
        :rtype: str
        """
        return self._deprecation_state

    @deprecation_state.setter
    def deprecation_state(self, deprecation_state):
        """
        Sets the deprecation_state of this CRSDeprecationInfo.
        State - one of {identical, corrected, unresolved}

        :param deprecation_state: The deprecation_state of this CRSDeprecationInfo.
        :type: str
        """

        self._deprecation_state = deprecation_state

    @property
    def remarks(self):
        """
        Gets the remarks of this CRSDeprecationInfo.
        Further explanation of the deprecation.

        :return: The remarks of this CRSDeprecationInfo.
        :rtype: str
        """
        return self._remarks

    @remarks.setter
    def remarks(self, remarks):
        """
        Sets the remarks of this CRSDeprecationInfo.
        Further explanation of the deprecation.

        :param remarks: The remarks of this CRSDeprecationInfo.
        :type: str
        """

        self._remarks = remarks

    @property
    def superseded_by_crs(self):
        """
        Gets the superseded_by_crs of this CRSDeprecationInfo.
        The coordinate reference system to be used instead - if any is recommended.

        :return: The superseded_by_crs of this CRSDeprecationInfo.
        :rtype: CRS
        """
        return self._superseded_by_crs

    @superseded_by_crs.setter
    def superseded_by_crs(self, superseded_by_crs):
        """
        Sets the superseded_by_crs of this CRSDeprecationInfo.
        The coordinate reference system to be used instead - if any is recommended.

        :param superseded_by_crs: The superseded_by_crs of this CRSDeprecationInfo.
        :type: CRS
        """

        self._superseded_by_crs = superseded_by_crs

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CRSDeprecationInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
