# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EarlyBoundCRSEssence(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'name': 'str',
        'ver': 'str',
        'late_bound_crs': 'LateBoundCRSEssence',
        'single_ct': 'SingleCTEssence',
        'compound_ct': 'CompoundCTEssence',
        'auth_code': 'AuthCode'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'ver': 'ver',
        'late_bound_crs': 'lateBoundCRS',
        'single_ct': 'singleCT',
        'compound_ct': 'compoundCT',
        'auth_code': 'authCode'
    }

    def __init__(self, type='EBC', name=None, ver=None, late_bound_crs=None, single_ct=None, compound_ct=None, auth_code=None):
        """
        EarlyBoundCRSEssence - a model defined in Swagger
        """

        self._type = None
        self._name = None
        self._ver = None
        self._late_bound_crs = None
        self._single_ct = None
        self._compound_ct = None
        self._auth_code = None

        self.type = type
        self.name = name
        if ver is not None:
          self.ver = ver
        self.late_bound_crs = late_bound_crs
        if single_ct is not None:
          self.single_ct = single_ct
        if compound_ct is not None:
          self.compound_ct = compound_ct
        if auth_code is not None:
          self.auth_code = auth_code

    @property
    def type(self):
        """
        Gets the type of this EarlyBoundCRSEssence.
        The type identifier, fixed to 'EBC'.

        :return: The type of this EarlyBoundCRSEssence.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this EarlyBoundCRSEssence.
        The type identifier, fixed to 'EBC'.

        :param type: The type of this EarlyBoundCRSEssence.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")
        allowed_values = ["EBC"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def name(self):
        """
        Gets the name of this EarlyBoundCRSEssence.
        The name of the early-bound coordinate reference system.

        :return: The name of this EarlyBoundCRSEssence.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this EarlyBoundCRSEssence.
        The name of the early-bound coordinate reference system.

        :param name: The name of this EarlyBoundCRSEssence.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def ver(self):
        """
        Gets the ver of this EarlyBoundCRSEssence.
        The engine version issuing the definition.

        :return: The ver of this EarlyBoundCRSEssence.
        :rtype: str
        """
        return self._ver

    @ver.setter
    def ver(self, ver):
        """
        Sets the ver of this EarlyBoundCRSEssence.
        The engine version issuing the definition.

        :param ver: The ver of this EarlyBoundCRSEssence.
        :type: str
        """

        self._ver = ver

    @property
    def late_bound_crs(self):
        """
        Gets the late_bound_crs of this EarlyBoundCRSEssence.
        Late-bound CRS, which is bound to a single (st) or compound (ct) transformation to WGS 84.

        :return: The late_bound_crs of this EarlyBoundCRSEssence.
        :rtype: LateBoundCRSEssence
        """
        return self._late_bound_crs

    @late_bound_crs.setter
    def late_bound_crs(self, late_bound_crs):
        """
        Sets the late_bound_crs of this EarlyBoundCRSEssence.
        Late-bound CRS, which is bound to a single (st) or compound (ct) transformation to WGS 84.

        :param late_bound_crs: The late_bound_crs of this EarlyBoundCRSEssence.
        :type: LateBoundCRSEssence
        """
        if late_bound_crs is None:
            raise ValueError("Invalid value for `late_bound_crs`, must not be `None`")

        self._late_bound_crs = late_bound_crs

    @property
    def single_ct(self):
        """
        Gets the single_ct of this EarlyBoundCRSEssence.
        Single Transformation, which binds the late-bound CRS (lb) to WGS 84. If absent, a compound transformation (ct) must be present.

        :return: The single_ct of this EarlyBoundCRSEssence.
        :rtype: SingleCTEssence
        """
        return self._single_ct

    @single_ct.setter
    def single_ct(self, single_ct):
        """
        Sets the single_ct of this EarlyBoundCRSEssence.
        Single Transformation, which binds the late-bound CRS (lb) to WGS 84. If absent, a compound transformation (ct) must be present.

        :param single_ct: The single_ct of this EarlyBoundCRSEssence.
        :type: SingleCTEssence
        """

        self._single_ct = single_ct

    @property
    def compound_ct(self):
        """
        Gets the compound_ct of this EarlyBoundCRSEssence.
        Compound transformation, which binds the late-bound CRS (lb) to WGS 84. If absent, a single transformation (st) must be present.

        :return: The compound_ct of this EarlyBoundCRSEssence.
        :rtype: CompoundCTEssence
        """
        return self._compound_ct

    @compound_ct.setter
    def compound_ct(self, compound_ct):
        """
        Sets the compound_ct of this EarlyBoundCRSEssence.
        Compound transformation, which binds the late-bound CRS (lb) to WGS 84. If absent, a single transformation (st) must be present.

        :param compound_ct: The compound_ct of this EarlyBoundCRSEssence.
        :type: CompoundCTEssence
        """

        self._compound_ct = compound_ct

    @property
    def auth_code(self):
        """
        Gets the auth_code of this EarlyBoundCRSEssence.
        The authority code for this item.

        :return: The auth_code of this EarlyBoundCRSEssence.
        :rtype: AuthCode
        """
        return self._auth_code

    @auth_code.setter
    def auth_code(self, auth_code):
        """
        Sets the auth_code of this EarlyBoundCRSEssence.
        The authority code for this item.

        :param auth_code: The auth_code of this EarlyBoundCRSEssence.
        :type: AuthCode
        """

        self._auth_code = auth_code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EarlyBoundCRSEssence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
