# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class LateBoundCRS(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crstype': 'str',
        'source': 'str',
        'transformation_ready': 'bool',
        'base_crs_authority_code': 'AuthCode',
        'alias_names': 'list[str]',
        'axis_units': 'list[str]',
        'number_of_axes': 'int',
        'description': 'str',
        'last_modified': 'str',
        'area_of_use': 'AreaOfUse',
        'deprecation_info': 'CRSDeprecationInfo',
        'named_reference': 'NamedReference',
        'essence': 'LateBoundCRSEssence'
    }

    attribute_map = {
        'crstype': 'crstype',
        'source': 'source',
        'transformation_ready': 'transformationReady',
        'base_crs_authority_code': 'baseCRSAuthorityCode',
        'alias_names': 'aliasNames',
        'axis_units': 'axisUnits',
        'number_of_axes': 'numberOfAxes',
        'description': 'description',
        'last_modified': 'lastModified',
        'area_of_use': 'areaOfUse',
        'deprecation_info': 'deprecationInfo',
        'named_reference': 'namedReference',
        'essence': 'essence'
    }

    def __init__(self, crstype=None, source=None, transformation_ready=None, base_crs_authority_code=None, alias_names=None, axis_units=None, number_of_axes=None, description=None, last_modified=None, area_of_use=None, deprecation_info=None, named_reference=None, essence=None):
        """
        LateBoundCRS - a model defined in Swagger
        """

        self._crstype = None
        self._source = None
        self._transformation_ready = None
        self._base_crs_authority_code = None
        self._alias_names = None
        self._axis_units = None
        self._number_of_axes = None
        self._description = None
        self._last_modified = None
        self._area_of_use = None
        self._deprecation_info = None
        self._named_reference = None
        self._essence = None

        if crstype is not None:
          self.crstype = crstype
        if source is not None:
          self.source = source
        if transformation_ready is not None:
          self.transformation_ready = transformation_ready
        if base_crs_authority_code is not None:
          self.base_crs_authority_code = base_crs_authority_code
        if alias_names is not None:
          self.alias_names = alias_names
        if axis_units is not None:
          self.axis_units = axis_units
        if number_of_axes is not None:
          self.number_of_axes = number_of_axes
        if description is not None:
          self.description = description
        if last_modified is not None:
          self.last_modified = last_modified
        if area_of_use is not None:
          self.area_of_use = area_of_use
        if deprecation_info is not None:
          self.deprecation_info = deprecation_info
        if named_reference is not None:
          self.named_reference = named_reference
        if essence is not None:
          self.essence = essence

    @property
    def crstype(self):
        """
        Gets the crstype of this LateBoundCRS.
        The type of the LateBoundCRS.

        :return: The crstype of this LateBoundCRS.
        :rtype: str
        """
        return self._crstype

    @crstype.setter
    def crstype(self, crstype):
        """
        Sets the crstype of this LateBoundCRS.
        The type of the LateBoundCRS.

        :param crstype: The crstype of this LateBoundCRS.
        :type: str
        """

        self._crstype = crstype

    @property
    def source(self):
        """
        Gets the source of this LateBoundCRS.
        The source of the LateBoundCRS.

        :return: The source of this LateBoundCRS.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this LateBoundCRS.
        The source of the LateBoundCRS.

        :param source: The source of this LateBoundCRS.
        :type: str
        """

        self._source = source

    @property
    def transformation_ready(self):
        """
        Gets the transformation_ready of this LateBoundCRS.
        The Transformation readiness of the LateBoundCRS.

        :return: The transformation_ready of this LateBoundCRS.
        :rtype: bool
        """
        return self._transformation_ready

    @transformation_ready.setter
    def transformation_ready(self, transformation_ready):
        """
        Sets the transformation_ready of this LateBoundCRS.
        The Transformation readiness of the LateBoundCRS.

        :param transformation_ready: The transformation_ready of this LateBoundCRS.
        :type: bool
        """

        self._transformation_ready = transformation_ready

    @property
    def base_crs_authority_code(self):
        """
        Gets the base_crs_authority_code of this LateBoundCRS.
        The base authority code of the LateBoundCRS.

        :return: The base_crs_authority_code of this LateBoundCRS.
        :rtype: AuthCode
        """
        return self._base_crs_authority_code

    @base_crs_authority_code.setter
    def base_crs_authority_code(self, base_crs_authority_code):
        """
        Sets the base_crs_authority_code of this LateBoundCRS.
        The base authority code of the LateBoundCRS.

        :param base_crs_authority_code: The base_crs_authority_code of this LateBoundCRS.
        :type: AuthCode
        """

        self._base_crs_authority_code = base_crs_authority_code

    @property
    def alias_names(self):
        """
        Gets the alias_names of this LateBoundCRS.
        Alias names for this LateBoundCRS.

        :return: The alias_names of this LateBoundCRS.
        :rtype: list[str]
        """
        return self._alias_names

    @alias_names.setter
    def alias_names(self, alias_names):
        """
        Sets the alias_names of this LateBoundCRS.
        Alias names for this LateBoundCRS.

        :param alias_names: The alias_names of this LateBoundCRS.
        :type: list[str]
        """

        self._alias_names = alias_names

    @property
    def axis_units(self):
        """
        Gets the axis_units of this LateBoundCRS.
        Axis Unit Essences.

        :return: The axis_units of this LateBoundCRS.
        :rtype: list[str]
        """
        return self._axis_units

    @axis_units.setter
    def axis_units(self, axis_units):
        """
        Sets the axis_units of this LateBoundCRS.
        Axis Unit Essences.

        :param axis_units: The axis_units of this LateBoundCRS.
        :type: list[str]
        """

        self._axis_units = axis_units

    @property
    def number_of_axes(self):
        """
        Gets the number_of_axes of this LateBoundCRS.
        The NumberOfAxes of the LateBoundCRS.

        :return: The number_of_axes of this LateBoundCRS.
        :rtype: int
        """
        return self._number_of_axes

    @number_of_axes.setter
    def number_of_axes(self, number_of_axes):
        """
        Sets the number_of_axes of this LateBoundCRS.
        The NumberOfAxes of the LateBoundCRS.

        :param number_of_axes: The number_of_axes of this LateBoundCRS.
        :type: int
        """

        self._number_of_axes = number_of_axes

    @property
    def description(self):
        """
        Gets the description of this LateBoundCRS.
        The description of the LateBoundCRS.

        :return: The description of this LateBoundCRS.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this LateBoundCRS.
        The description of the LateBoundCRS.

        :param description: The description of this LateBoundCRS.
        :type: str
        """

        self._description = description

    @property
    def last_modified(self):
        """
        Gets the last_modified of this LateBoundCRS.
        The LastModified of the LateBoundCRS.

        :return: The last_modified of this LateBoundCRS.
        :rtype: str
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """
        Sets the last_modified of this LateBoundCRS.
        The LastModified of the LateBoundCRS.

        :param last_modified: The last_modified of this LateBoundCRS.
        :type: str
        """

        self._last_modified = last_modified

    @property
    def area_of_use(self):
        """
        Gets the area_of_use of this LateBoundCRS.
        The Area of Use for this CRS.

        :return: The area_of_use of this LateBoundCRS.
        :rtype: AreaOfUse
        """
        return self._area_of_use

    @area_of_use.setter
    def area_of_use(self, area_of_use):
        """
        Sets the area_of_use of this LateBoundCRS.
        The Area of Use for this CRS.

        :param area_of_use: The area_of_use of this LateBoundCRS.
        :type: AreaOfUse
        """

        self._area_of_use = area_of_use

    @property
    def deprecation_info(self):
        """
        Gets the deprecation_info of this LateBoundCRS.
        Only if deprecated - additional information and potentially a recommended replacement CRS.

        :return: The deprecation_info of this LateBoundCRS.
        :rtype: CRSDeprecationInfo
        """
        return self._deprecation_info

    @deprecation_info.setter
    def deprecation_info(self, deprecation_info):
        """
        Sets the deprecation_info of this LateBoundCRS.
        Only if deprecated - additional information and potentially a recommended replacement CRS.

        :param deprecation_info: The deprecation_info of this LateBoundCRS.
        :type: CRSDeprecationInfo
        """

        self._deprecation_info = deprecation_info

    @property
    def named_reference(self):
        """
        Gets the named_reference of this LateBoundCRS.
        A structure containing the item Name and the persistable Reference string; populated if the request mode='persistable_reference'.

        :return: The named_reference of this LateBoundCRS.
        :rtype: NamedReference
        """
        return self._named_reference

    @named_reference.setter
    def named_reference(self, named_reference):
        """
        Sets the named_reference of this LateBoundCRS.
        A structure containing the item Name and the persistable Reference string; populated if the request mode='persistable_reference'.

        :param named_reference: The named_reference of this LateBoundCRS.
        :type: NamedReference
        """

        self._named_reference = named_reference

    @property
    def essence(self):
        """
        Gets the essence of this LateBoundCRS.
        The Essence of the LateBoundCRS; populated if the request mode='essence'.

        :return: The essence of this LateBoundCRS.
        :rtype: LateBoundCRSEssence
        """
        return self._essence

    @essence.setter
    def essence(self, essence):
        """
        Sets the essence of this LateBoundCRS.
        The Essence of the LateBoundCRS; populated if the request mode='essence'.

        :param essence: The essence of this LateBoundCRS.
        :type: LateBoundCRSEssence
        """

        self._essence = essence

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, LateBoundCRS):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
