# coding: utf-8

"""
    CRS Catalog Service API

    Coordinate Reference System (CRS) Catalog Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.any_crs_essence import AnyCRSEssence
from .models.any_ct_essence import AnyCTEssence
from .models.area_of_use import AreaOfUse
from .models.area_of_use_deprecation_info import AreaOfUseDeprecationInfo
from .models.area_of_use_essence import AreaOfUseEssence
from .models.area_of_use_request import AreaOfUseRequest
from .models.area_of_use_results import AreaOfUseResults
from .models.auth_code import AuthCode
from .models.bound_box import BoundBox
from .models.crs import CRS
from .models.crs_deprecation_info import CRSDeprecationInfo
from .models.crs_request import CRSRequest
from .models.crs_results import CRSResults
from .models.ct import CT
from .models.ct_deprecation_info import CTDeprecationInfo
from .models.ct_request import CTRequest
from .models.ct_results import CTResults
from .models.catalog import Catalog
from .models.catalog_attributes import CatalogAttributes
from .models.compound_crs import CompoundCRS
from .models.compound_crs_essence import CompoundCRSEssence
from .models.compound_crs_request import CompoundCRSRequest
from .models.compound_crs_results import CompoundCRSResults
from .models.compound_ct import CompoundCT
from .models.compound_ct_essence import CompoundCTEssence
from .models.compound_ct_request import CompoundCTRequest
from .models.compound_ct_results import CompoundCTResults
from .models.early_bound_crs import EarlyBoundCRS
from .models.early_bound_crs_essence import EarlyBoundCRSEssence
from .models.early_bound_crs_request import EarlyBoundCRSRequest
from .models.early_bound_crs_results import EarlyBoundCRSResults
from .models.error_response import ErrorResponse
from .models.late_bound_crs import LateBoundCRS
from .models.late_bound_crs_essence import LateBoundCRSEssence
from .models.late_bound_crs_request import LateBoundCRSRequest
from .models.late_bound_crs_results import LateBoundCRSResults
from .models.named_reference import NamedReference
from .models.search_area_of_use_request import SearchAreaOfUseRequest
from .models.search_crs_request import SearchCRSRequest
from .models.search_ct_request import SearchCTRequest
from .models.single_ct import SingleCT
from .models.single_ct_essence import SingleCTEssence
from .models.single_ct_request import SingleCTRequest
from .models.single_ct_results import SingleCTResults

# import apis into sdk package
from .apis.areas_of_use_api import AreasOfUseApi
from .apis.crs_catalog_api import CRSCatalogApi
from .apis.cartographic_transformations_api import CartographicTransformationsApi
from .apis.coordinate_reference_systems_api import CoordinateReferenceSystemsApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
