variables:
  GC_SERVICE: crs-catalog
  GC_VENDOR: gc
  GC_INT_TEST_TYPE: python
  GC_PYTHON_INT_TEST_SUBDIR: testing/catalog_test_gc
  # --- baremetal specific variables ---
  GC_BAREMETAL_PYTHON_INT_TEST_SUBDIR: testing/catalog_test_baremetal
  # --- end of baremetal specific variables ---

gc-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $GC_CRS_CATALOG_HOSTNAME

gc-dev2-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $GC_CRS_CATALOG_HOSTNAME

gc-baremetal-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_BAREMETAL_CRS_CATALOG_HOSTNAME
