data:
  # common
  logLevel: "INFO"
  javaAppJar: "/deployments/*-spring-boot.jar"
  serverPort: 8080
  # ibm
  contextPath: "/api/crs/catalog"
  beanDefOverriding: true
  acceptHttp: true
  logPrefix: crs-catalog
  cacheExpiration: 9000
  cahceMaxSize: 2000
  healthCheckUri: "/api/crs/catalog/v2/info,/api/crs/catalog/v2/api-docs"
  loggingLevelOsdu: debug
  loggingLevelSpring: debug
  #authorization
  authorizeAPI: http://TBD:8080/api/entitlements/v2
  deployEnv: CLOUD
  #db
  dbURL: http://tbd:5984
  #get-from-existing secret
  dbUser: admin
#keycloack
  keycloakUrl: tbd
  keycloakRealm: OSDU
  keycloakUserEmail: admin-sa@ibm.com
  keycloakUsername: admin-sa
  keycloakPassword: changeit
  keycloakClientId: osdu-login
  keycloakClientSecret: referenv 
  #move to secre. do not commit.
  #get-from-existing secret  
  dbPassw: tbd
  #get-from-svc-name-template
  patitionAPI: http://tbd:8080/api/partition/v1
  policyAPI: http://tbd:8080/api/policy/v1
  grantType: password
 #partition
  pKCEndPointHost: tbd
  pKCClientId: partition-service
  pKCClientSecret: tbd
  pKCGrantType: password
  pKCUser: partition-service-admin
  pKCPassword: changeit
  pKCRealm: OSDU
  pKAcceptHttp: true
  tenantCacheExpiryInSec: 10000
  #make java options conditional in template
  ibmElasticHost: elasticsearch-master
  ibmElasticPort: 9200
  ibmElasticUser: ""
  ibmElasticPassword: ""
  # AmQP
  amqpPassword: TBD
  amqpUserName: TBD
  amqpURL: "amqp://ex-aao-amqp-0-svc:5672"
conf:
  configmap: "crs-catalog-config"
