LOG_PREFIX=crs-catalog

server.servlet.contextPath=/api/crs/catalog/
logging.level.org.springframework.web=DEBUG
server.port=8080
#spring.cloud.gcp.project-id=opendes
#spring.security.user.roles=service.crs.admin
JAVA_HEAP_OPTS=-Xms4096M -Xmx4096M
JAVA_GC_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitiatingHeapOccupancyPercent=45

azure.activedirectory.app-resource-id=${aad_client_id}
azure.keyvault.url=${KEYVAULT_URI}

spring.application.name=crs-catalog
spring.main.allow-bean-definition-overriding=true

# Entitlement properties
#
#
# [Required] URL of the Entitlements Service
osdu.entitlement.url=${ENTITLEMENT_URL}
azure.eventgrid.manager.enabled=false
azure.eventgrid.topic.enabled=false
azure.cryptography.enabled=false

# Other properties
#
#
# [Optional] [AKS] [GKE] File location of the crs catalog
osdu.crs.catalog.filename=${CRS_CATALOG_FILENAME:/mnt/crs_catalogs/crs_catalog_v2.json}
# CRS_CATALOG_FILENAME=C:\\osdu-delfi\\crs-catalog-service\\data\\crs_catalog_v2.json

# ENTITLEMENT_URL=${ENTITLEMENT_URL}
# CRS_CATALOG_FILENAME=C:\\osdu-delfi\\crs-catalog-service\\data\\crs_catalog_v2.json

# Azure App Insights configuration
azure.application-insights.instrumentation-key=${appinsights_key}

#logging configuration
logging.transaction.enabled=true
logging.slf4jlogger.enabled=true
logging.mdccontext.enabled=true
